import { Mail, MapPin, Pencil, Plus, Search, StickyNote, Trash2 } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { Button } from '../../../components/ui/button'
import { Dialog } from '../../../components/ui/dialog'
import { Input } from '../../../components/ui/input'

type Customer = { id: string; name: string; phone: string; email: string; address: string; note: string; status: 'Activo' | 'Inactivo' }
const initialCustomers: Customer[] = [
  { id: 'CLI-001', name: 'Imprenta Gráfica Norte S.A.C.', phone: '987 654 321', email: 'compras@graficanorte.pe', address: 'Av. Argentina 1540, Callao', note: 'Cliente frecuente. Entregas por la mañana.', status: 'Activo' },
  { id: 'CLI-002', name: 'Empaques del Pacífico S.R.L.', phone: '956 204 118', email: 'logistica@empaquespacifico.pe', address: 'Jr. Los Industriales 420, Ate', note: 'Solicita cotización antes de cada pedido.', status: 'Activo' },
  { id: 'CLI-003', name: 'Distribuidora San Martín E.I.R.L.', phone: '944 870 565', email: 'ventas@distsanmartin.pe', address: 'Calle Las Begonias 275, San Isidro', note: 'Atención a crédito sujeta a aprobación.', status: 'Activo' },
  { id: 'CLI-004', name: 'Editorial Andina S.A.C.', phone: '01 463 8890', email: 'contacto@editorialandina.pe', address: 'Av. Nicolás Arriola 811, La Victoria', note: 'Cliente temporalmente sin operaciones.', status: 'Inactivo' },
]
const emptyCustomer = (): Customer => ({ id: '', name: '', phone: '', email: '', address: '', note: '', status: 'Activo' })

export function CustomersPage() {
  const [customers, setCustomers] = useState(initialCustomers); const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Customer | null>(null)
  const visible = useMemo(() => customers.filter(customer => (customer.name + customer.phone + customer.email + customer.address).toLowerCase().includes(query.toLowerCase())), [customers, query])
  const save = (customer: Customer) => setCustomers(current => customer.id ? current.map(item => item.id === customer.id ? customer : item) : [{ ...customer, id: 'CLI-' + String(current.length + 1).padStart(3, '0') }, ...current]); const remove = (id: string) => setCustomers(current => current.filter(customer => customer.id !== id))
  return <div className="mx-auto max-w-none"><section className="rounded-[10px] border border-border bg-white p-6 shadow-card"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-sm font-semibold">Clientes</h1><p className="mt-1 text-xs text-muted">Cartera de clientes, contactos e información comercial.</p></div><Button size="sm" onClick={() => setEditing(emptyCustomer())}><Plus className="h-4 w-4" />Nuevo Cliente</Button></header><div className="relative mt-5 max-w-sm"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted" /><Input value={query} onChange={event => setQuery(event.target.value)} className="h-9 pl-9" placeholder="Buscar cliente, celular o correo…" /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="bg-[#f7f9fc] text-[11px] uppercase tracking-[.5px] text-muted">{['Razón social', 'Celular', 'Correo', 'Dirección', 'Estado', ''].map(item => <th className="border-y border-border px-4 py-3 font-semibold" key={item}>{item}</th>)}</tr></thead><tbody>{visible.map(customer => <tr key={customer.id} className="border-b border-border text-[13px] text-slate-700"><td className="px-4 py-3.5 font-medium">{customer.name}</td><td className="px-4 py-3.5 font-mono text-xs">{customer.phone}</td><td className="px-4 py-3.5">{customer.email}</td><td className="px-4 py-3.5 text-slate-600">{customer.address}</td><td className="px-4 py-3.5"><span className={customer.status === 'Activo' ? 'rounded-full bg-emerald-100 px-2.5 py-1 text-[11px] font-semibold text-emerald-700' : 'rounded-full bg-red-100 px-2.5 py-1 text-[11px] font-semibold text-red-700'}>{customer.status}</span></td><td className="px-4 py-3.5 text-right"><button type="button" onClick={() => setEditing(customer)} title="Editar cliente" aria-label="Editar cliente" className="inline-flex h-9 w-10 items-center justify-center rounded-md border border-border bg-white text-slate-700"><Pencil className="h-3.5 w-3.5" /></button><button type="button" onClick={() => remove(customer.id)} title="Eliminar cliente" aria-label="Eliminar cliente" className="ml-1 inline-flex h-9 w-10 items-center justify-center rounded-md border border-red-300 bg-red-50 text-red-500"><Trash2 className="h-3.5 w-3.5" /></button></td></tr>)}{!visible.length && <tr><td colSpan={6} className="p-10 text-center text-sm text-muted">No se encontraron clientes.</td></tr>}</tbody></table></div></section>{editing && <CustomerDialog customer={editing} onClose={() => setEditing(null)} onSave={customer => { save(customer); setEditing(null) }} />}</div>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-[.4px] text-slate-600">{label}</span>{children}</label> }
function CustomerDialog({ customer, onClose, onSave }: { customer: Customer; onClose: () => void; onSave: (customer: Customer) => void }) {
  const [draft, setDraft] = useState(customer); const patch = (value: Partial<Customer>) => setDraft(current => ({ ...current, ...value }))
  const submit = (event: FormEvent) => { event.preventDefault(); if (!draft.name.trim() || !draft.phone.trim() || !draft.email.trim() || !draft.address.trim()) return; onSave({ ...draft, name: draft.name.trim(), phone: draft.phone.trim(), email: draft.email.trim(), address: draft.address.trim(), note: draft.note.trim() }) }
  return <Dialog open title={customer.id ? 'Editar cliente' : 'Nuevo cliente'} onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>Cancelar</Button><Button type="submit" form="customer-form">{customer.id ? 'Guardar cambios' : 'Registrar cliente'}</Button></>}><form id="customer-form" onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre o razón social *"><Input required value={draft.name} placeholder="Ej. Empresa Gráfica S.A.C." onChange={event => patch({ name: event.target.value })} /></Field><Field label="Celular *"><Input required value={draft.phone} placeholder="987 654 321" onChange={event => patch({ phone: event.target.value })} /></Field><Field label="Correo electrónico *"><Input required type="email" value={draft.email} placeholder="contacto@empresa.pe" onChange={event => patch({ email: event.target.value })} /></Field><Field label="Estado"><select value={draft.status} onChange={event => patch({ status: event.target.value as Customer['status'] })} className="h-10 w-full rounded-md border border-border bg-[#f4f7fb] px-3 text-sm outline-none focus:border-brand focus:ring-1 focus:ring-brand"><option>Activo</option><option>Inactivo</option></select></Field></div><Field label="Dirección *"><div className="relative"><MapPin className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input required value={draft.address} className="pl-9" placeholder="Dirección fiscal o de entrega" onChange={event => patch({ address: event.target.value })} /></div></Field><Field label="Notas"><div className="relative"><StickyNote className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" /><textarea value={draft.note} className="min-h-24 w-full rounded-md border border-border bg-[#f4f7fb] py-2.5 pl-9 pr-3 text-sm outline-none focus:border-brand focus:bg-white focus:ring-1 focus:ring-brand" placeholder="Observaciones comerciales del cliente..." onChange={event => patch({ note: event.target.value })} /></div></Field><div className="flex items-center gap-2 rounded-md border border-blue-100 bg-blue-50/50 p-3 text-xs text-slate-600"><Mail className="h-3.5 w-3.5 text-brand" />Información disponible para comunicaciones y cotizaciones.</div></form></Dialog>
}
