import { Mail, MapPin, Pencil, Plus, Search, StickyNote, Trash2 } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Button } from '../../../components/ui/button'
import { Dialog } from '../../../components/ui/dialog'
import { Input } from '../../../components/ui/input'
import { createCustomer, deleteCustomer, listCustomers, type Customer, type CustomerStatus, updateCustomer } from '../services/customer-api.service'

const emptyCustomer = (): Omit<Customer, 'id'> => ({ name: '', phone: '', email: '', address: '', note: '', status: 'Activo' })
const sortCustomers = (items: Customer[]) => [...items].sort((left, right) => left.name.localeCompare(right.name, 'es'))

export function CustomersPage() {
  const queryClient = useQueryClient(); const customersQuery = useQuery({ queryKey: ['customers'], queryFn: listCustomers }); const customers = customersQuery.data ?? []
  const [query, setQuery] = useState(''); const [modalItem, setModalItem] = useState<Customer | null | undefined>(undefined); const [notice, setNotice] = useState('')
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2800) }
  const saveMutation = useMutation({ mutationFn: ({ item, editing }: { item: Omit<Customer, 'id'>; editing?: Customer }) => editing ? updateCustomer(editing.id, item) : createCustomer(item), onSuccess: saved => { queryClient.setQueryData<Customer[]>(['customers'], current => sortCustomers([...(current ?? []).filter(item => item.id !== saved.id), saved])); void queryClient.invalidateQueries({ queryKey: ['customers'] }); setQuery(''); setModalItem(undefined); notify('Cliente guardado y sincronizado con la base de datos') }, onError: error => notify(error instanceof Error ? error.message : 'No se pudo guardar el cliente') })
  const removeMutation = useMutation({ mutationFn: deleteCustomer, onSuccess: (_, id) => { queryClient.setQueryData<Customer[]>(['customers'], current => current?.filter(item => item.id !== id) ?? []); void queryClient.invalidateQueries({ queryKey: ['customers'] }); notify('Cliente eliminado de la base de datos') }, onError: error => notify(error instanceof Error ? error.message : 'No se pudo eliminar el cliente') })
  const visible = useMemo(() => customers.filter(customer => `${customer.name} ${customer.phone} ${customer.email} ${customer.address}`.toLowerCase().includes(query.toLowerCase())), [customers, query])

  return <div className="mx-auto max-w-none"><section className="rounded-[10px] border border-border bg-white p-6 shadow-card"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-sm font-semibold">Clientes</h1><p className="mt-1 text-xs text-muted">Cartera de clientes, contactos e información comercial.</p></div><Button size="sm" onClick={() => setModalItem(null)}><Plus className="h-4 w-4" />Nuevo Cliente</Button></header><div className="relative mt-5 max-w-sm"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted" /><Input value={query} onChange={event => setQuery(event.target.value)} className="h-9 pl-9" placeholder="Buscar cliente, celular o correo…" /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="bg-[#f7f9fc] text-[11px] uppercase tracking-[.5px] text-muted">{['Razón social', 'Celular', 'Correo', 'Dirección', 'Estado', ''].map(item => <th className="border-y border-border px-4 py-3 font-semibold" key={item}>{item}</th>)}</tr></thead><tbody>{customersQuery.isLoading ? <tr><td colSpan={6} className="p-10 text-center text-sm text-muted">Cargando clientes desde la base de datos…</td></tr> : customersQuery.isError ? <tr><td colSpan={6} className="p-10 text-center text-sm text-red-600">No se pudieron cargar los clientes.</td></tr> : visible.length ? visible.map(customer => <tr key={customer.id} className="border-b border-border text-[13px] text-slate-700"><td className="px-4 py-3.5 font-medium">{customer.name}</td><td className="px-4 py-3.5 font-mono text-xs">{customer.phone}</td><td className="px-4 py-3.5">{customer.email}</td><td className="px-4 py-3.5 text-slate-600">{customer.address}</td><td className="px-4 py-3.5"><StatusBadge status={customer.status} /></td><td className="px-4 py-3.5 text-right"><IconButton label="Editar cliente" onClick={() => setModalItem(customer)}><Pencil className="h-3.5 w-3.5" /></IconButton><IconButton label="Eliminar cliente" danger onClick={() => removeMutation.mutate(customer.id)}><Trash2 className="h-3.5 w-3.5" /></IconButton></td></tr>) : <tr><td colSpan={6} className="p-10 text-center text-sm text-muted">No se encontraron clientes.</td></tr>}</tbody></table></div></section>{modalItem !== undefined && <CustomerDialog item={modalItem ?? undefined} onClose={() => setModalItem(undefined)} onSave={async item => { await saveMutation.mutateAsync({ item, editing: modalItem ?? undefined }).catch(() => undefined) }} />}{notice && <div className="fixed bottom-6 right-6 z-[60] rounded-md border border-border border-l-4 border-l-emerald-600 bg-white px-4 py-3 text-sm shadow-panel">{notice}</div>}</div>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-[.4px] text-slate-600">{label}</span>{children}</label> }
function CustomerDialog({ item, onClose, onSave }: { item?: Customer; onClose: () => void; onSave: (customer: Omit<Customer, 'id'>) => Promise<void> }) {
  const [draft, setDraft] = useState<Omit<Customer, 'id'>>(item ? { name: item.name, phone: item.phone, email: item.email, address: item.address, note: item.note, status: item.status } : emptyCustomer()); const [saving, setSaving] = useState(false); const patch = (value: Partial<Omit<Customer, 'id'>>) => setDraft(current => ({ ...current, ...value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await onSave({ ...draft, name: draft.name.trim(), phone: draft.phone.trim(), email: draft.email.trim(), address: draft.address.trim(), note: draft.note.trim() }) } finally { setSaving(false) } }
  return <Dialog open title={item ? 'Editar cliente' : 'Nuevo cliente'} onClose={onClose} footer={<><Button variant="outline" onClick={onClose} disabled={saving}>Cancelar</Button><Button type="submit" form="customer-form" disabled={saving}>{saving ? 'Guardando…' : item ? 'Guardar cambios' : 'Registrar cliente'}</Button></>}><form id="customer-form" onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre o razón social *"><Input required value={draft.name} placeholder="Ej. Empresa Gráfica S.A.C." onChange={event => patch({ name: event.target.value })} /></Field><Field label="Celular *"><Input required value={draft.phone} placeholder="987 654 321" onChange={event => patch({ phone: event.target.value })} /></Field><Field label="Correo electrónico *"><Input required type="email" value={draft.email} placeholder="contacto@empresa.pe" onChange={event => patch({ email: event.target.value })} /></Field><Field label="Estado"><select value={draft.status} onChange={event => patch({ status: event.target.value as CustomerStatus })} className="h-10 w-full rounded-md border border-border bg-[#f4f7fb] px-3 text-sm outline-none focus:border-brand focus:ring-1 focus:ring-brand"><option>Activo</option><option>Inactivo</option></select></Field></div><Field label="Dirección *"><div className="relative"><MapPin className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input required value={draft.address} className="pl-9" placeholder="Dirección fiscal o de entrega" onChange={event => patch({ address: event.target.value })} /></div></Field><Field label="Notas"><div className="relative"><StickyNote className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" /><textarea value={draft.note} className="min-h-24 w-full rounded-md border border-border bg-[#f4f7fb] py-2.5 pl-9 pr-3 text-sm outline-none focus:border-brand focus:bg-white focus:ring-1 focus:ring-brand" placeholder="Observaciones comerciales del cliente..." onChange={event => patch({ note: event.target.value })} /></div></Field><div className="flex items-center gap-2 rounded-md border border-blue-100 bg-blue-50/50 p-3 text-xs text-slate-600"><Mail className="h-3.5 w-3.5 text-brand" />Información disponible para comunicaciones y cotizaciones.</div></form></Dialog>
}
function StatusBadge({ status }: { status: CustomerStatus }) { return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${status === 'Activo' ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'}`}>{status}</span> }
function IconButton({ children, label, danger, onClick }: { children: React.ReactNode; label: string; danger?: boolean; onClick: () => void }) { return <button title={label} aria-label={label} onClick={onClick} className={`ml-1 inline-flex h-9 w-10 items-center justify-center rounded-md border ${danger ? 'border-red-300 bg-red-50 text-red-500' : 'border-border bg-white text-slate-700'}`}>{children}</button> }
