import { useState } from 'react'
import { Brackets, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { Button } from '../../../components/ui/button'
import { Dialog } from '../../../components/ui/dialog'
import { Input } from '../../../components/ui/input'
import type { AttributeDefinition, ProductStatus } from '../types/product.types'

const empty = (): AttributeDefinition => ({ id: crypto.randomUUID(), code: '', name: '', type: 'Texto', suffix: '', status: 'Activo' })
const Status = ({ status }: { status: ProductStatus }) => <span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${status === 'Activo' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{status}</span>

export function AttributeCatalog({ attributes, onNew, onEdit, onDelete }: { attributes: AttributeDefinition[]; onNew: () => void; onEdit: (attribute: AttributeDefinition) => void; onDelete: (id: string) => void }) {
  const [search, setSearch] = useState(''); const filtered = attributes.filter(attribute => `${attribute.code} ${attribute.name}`.toLowerCase().includes(search.toLowerCase()))
  return <section className="rounded-xl border border-border bg-white p-5 shadow-card"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-sm font-semibold">Catálogo de atributos</h1><p className="mt-1 text-xs text-muted">Crea cada atributo una sola vez; luego se podrá asociar desde la configuración de categorías.</p></div><Button size="sm" onClick={onNew}><Plus className="h-4 w-4" />Nuevo atributo</Button></header><div className="relative mt-5 max-w-md"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted" /><Input className="h-9 pl-9" value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar por nombre o código…" /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead className="bg-[#f7f9fc] text-[11px] uppercase tracking-[.5px] text-muted"><tr><th className="border-y border-border px-4 py-3">Código</th><th className="border-y border-border px-4 py-3">Atributo</th><th className="border-y border-border px-4 py-3">Tipo de dato</th><th className="border-y border-border px-4 py-3">Unidad / sufijo</th><th className="border-y border-border px-4 py-3">Estado</th><th className="border-y border-border px-4 py-3" /></tr></thead><tbody>{filtered.length ? filtered.map(attribute => <tr key={attribute.id} className="border-b border-border text-sm"><td className="px-4 py-3 font-mono text-xs font-bold text-brand">{attribute.code}</td><td className="px-4 py-3 font-medium">{attribute.name}</td><td className="px-4 py-3 text-slate-600">{attribute.type}</td><td className="px-4 py-3 text-slate-600">{attribute.suffix || '—'}</td><td className="px-4 py-3"><Status status={attribute.status} /></td><td className="px-4 py-3 text-right"><button onClick={() => onEdit(attribute)} className="rounded-md p-2 text-slate-600 hover:bg-blue-50 hover:text-brand" aria-label={`Editar ${attribute.name}`}><Pencil className="h-4 w-4" /></button><button onClick={() => onDelete(attribute.id)} className="rounded-md p-2 text-red-600 hover:bg-red-50" aria-label={`Eliminar ${attribute.name}`}><Trash2 className="h-4 w-4" /></button></td></tr>) : <tr><td colSpan={6} className="p-10 text-center text-sm text-muted">No hay atributos que coincidan.</td></tr>}</tbody></table></div></section>
}

export function AttributeDefinitionDialog({ item, onClose, onSave }: { item?: AttributeDefinition; onClose: () => void; onSave: (attribute: AttributeDefinition) => void }) {
  const [attribute, setAttribute] = useState<AttributeDefinition>(item ?? empty())
  return <Dialog open title={item ? `Editar atributo · ${item.name}` : 'Nuevo atributo'} onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>Cancelar</Button><Button form="attribute-definition-form" type="submit">{item ? 'Guardar cambios' : 'Crear atributo'}</Button></>}><form id="attribute-definition-form" onSubmit={event => { event.preventDefault(); if (attribute.name.trim() && attribute.code.trim()) onSave({ ...attribute, name: attribute.name.trim(), code: attribute.code.trim().toUpperCase(), suffix: attribute.suffix.trim() }) }} className="grid gap-4 md:grid-cols-2"><Field label="Nombre *"><Input value={attribute.name} onChange={event => setAttribute(current => ({ ...current, name: event.target.value }))} placeholder="Ej. Gramaje" required /></Field><Field label="Código *"><Input value={attribute.code} onChange={event => setAttribute(current => ({ ...current, code: event.target.value.toUpperCase() }))} placeholder="Ej. GRAMAJE" required /></Field><Field label="Tipo de dato *"><select value={attribute.type} onChange={event => setAttribute(current => ({ ...current, type: event.target.value as AttributeDefinition['type'] }))} className="h-10 w-full rounded-md border border-border bg-[#f4f7fb] px-3 text-sm"><option>Texto</option><option>Numérico</option></select></Field><Field label="Unidad / sufijo"><Input value={attribute.suffix} onChange={event => setAttribute(current => ({ ...current, suffix: event.target.value }))} placeholder="Ej. cm, mm, g/m²" /></Field><Field label="Estado"><select value={attribute.status} onChange={event => setAttribute(current => ({ ...current, status: event.target.value as ProductStatus }))} className="h-10 w-full rounded-md border border-border bg-[#f4f7fb] px-3 text-sm"><option>Activo</option><option>Inactivo</option></select></Field><p className="rounded-md border border-blue-100 bg-blue-50 p-3 text-xs text-slate-600 md:col-span-2">Este registro es global. La asociación a categorías y subcategorías se configura por separado.</p></form></Dialog>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-[.4px] text-slate-600">{label}</span>{children}</label> }
