import { useMemo, useState } from 'react'
import { Boxes, ClipboardList, SlidersHorizontal, Sparkles, Tags, X } from 'lucide-react'
import { Button } from '../../../components/ui/button'
import { Dialog } from '../../../components/ui/dialog'
import { Input } from '../../../components/ui/input'
import type { Attribute, ProductBase, ProductCategory, ProductRole, ProductStatus, ProductVariant, Unit } from '../types/product.types'

type SaveValue = { base: ProductBase; variants: ProductVariant[] }
type Props = { item?: ProductBase; variants?: ProductVariant[]; products: ProductBase[]; categories: ProductCategory[]; units: Unit[]; onClose: () => void; onSave: (value: SaveValue) => void | Promise<void>; presetSubcategoryId?: string; saveLabel?: string; floating?: boolean }
const roles: ProductRole[] = ['Mercadería', 'Insumo', 'Producto terminado']
const uid = () => crypto.randomUUID()
const num = (value: string, fallback: number) => Number.isFinite(Number(value)) ? Number(value) : fallback
const description = (attributes: Attribute[], values: Record<string, string>) => attributes.map(attribute => values[attribute.id]?.trim() ? `${values[attribute.id].trim()}${attribute.suffix ? ` ${attribute.suffix}` : ''}` : '').filter(Boolean).join(' · ')

export function ProductWizard({ item, variants = [], products, categories, units, onClose, onSave, presetSubcategoryId, saveLabel = 'Guardar producto', floating = false }: Props) {
  const variant = variants[0]
  const fixedCategory = categories.find(category => category.subcategories.some(subcategory => subcategory.id === presetSubcategoryId))
  const fixedSubcategory = fixedCategory?.subcategories.find(subcategory => subcategory.id === presetSubcategoryId)
  const [categoryId, setCategoryId] = useState(item?.categoryId ?? fixedCategory?.id ?? '')
  const [subcategoryId, setSubcategoryId] = useState(item?.subcategoryId ?? presetSubcategoryId ?? '')
  const [productRoles, setProductRoles] = useState<ProductRole[]>(item?.roles?.length ? item.roles : ['Mercadería'])
  const [status, setStatus] = useState<ProductStatus>(item?.status ?? 'Activo')
  const [attributes, setAttributes] = useState<Attribute[]>(item?.attributes ?? (fixedCategory && fixedSubcategory ? [...fixedCategory.attributes, ...fixedSubcategory.attributes] : []))
  const [values, setValues] = useState<Record<string, string>>(variant?.values ?? {})
  const [unit, setUnit] = useState(variant?.unit ?? units.find(unit => unit.status === 'Activo')?.code ?? '')
  const [factor, setFactor] = useState(String(variant?.factor ?? 1)); const [minimum, setMinimum] = useState(String(variant?.minimum ?? 0)); const [stock, setStock] = useState(String(variant?.stock ?? 0))
  const [automatic, setAutomatic] = useState(true); const [manualName, setManualName] = useState(item?.name ?? ''); const [error, setError] = useState('')
  const activeCategories = categories.filter(category => category.status === 'Activo'); const category = activeCategories.find(candidate => candidate.id === categoryId)
  const subcategories = category?.subcategories.filter(candidate => candidate.status === 'Activo' && (!candidate.isVariable || candidate.id === presetSubcategoryId)) ?? []; const subcategory = subcategories.find(candidate => candidate.id === subcategoryId)
  const generatedName = useMemo(() => [subcategory?.name ?? category?.name ?? 'Producto', description(attributes, values)].filter(Boolean).join(' · '), [attributes, category?.name, subcategory?.name, values])
  const name = automatic ? generatedName : manualName
  const selectCategory = (id: string) => { const next = activeCategories.find(value => value.id === id); setCategoryId(id); setSubcategoryId(''); setAttributes(next?.attributes ?? []); setValues({}) }
  const selectSubcategory = (id: string) => { const next = subcategories.find(value => value.id === id); setSubcategoryId(id); setAttributes([...(category?.attributes ?? []), ...(next?.attributes ?? [])]); setValues({}) }
  const save = async () => { const missing = attributes.find(attribute => attribute.required && !values[attribute.id]?.trim()); if (!category || (subcategories.length && !subcategory) || !productRoles.length || !unit || missing || !name.trim()) { setError(missing ? `Completa el atributo obligatorio: ${missing.name}.` : 'Completa los datos obligatorios del producto.'); return }; const base: ProductBase = { id: item?.id ?? uid(), code: item?.code ?? '', name, categoryId: category.id, categoryName: category.name, subcategoryId: subcategory?.id ?? null, subcategoryName: subcategory?.name ?? null, roles: productRoles, status, variantType: 'Básico', immediateConsumption: !productRoles.includes('Insumo'), attributes }; await onSave({ base, variants: [{ id: variant?.id ?? uid(), baseId: base.id, code: variant?.code ?? '', name, values, unit, factor: Math.max(.001, num(factor, 1)), minimum: Math.max(0, num(minimum, 0)), stock: Math.max(0, num(stock, 0)), status }] }) }
  const classification = <Section number="1" title="Clasificación" icon={Tags}><div className="grid gap-4 md:grid-cols-2"><Field label="Categoría *"><select value={categoryId} onChange={event => selectCategory(event.target.value)} className="input"><option value="">Selecciona categoría</option>{activeCategories.map(value => <option key={value.id} value={value.id}>{value.name}</option>)}</select></Field><Field label="Subcategoría"><select value={subcategoryId} onChange={event => selectSubcategory(event.target.value)} className="input" disabled={!category}><option value="">Selecciona subcategoría</option>{subcategories.map(value => <option key={value.id} value={value.id}>{value.name}</option>)}</select></Field></div><div className="mt-4 flex flex-wrap gap-2">{roles.map(role => <button key={role} type="button" onClick={() => setProductRoles(current => current.includes(role) ? current.filter(value => value !== role) : [...current, role])} className={`rounded-full border px-3 py-2 text-xs font-semibold ${productRoles.includes(role) ? 'border-brand bg-blue-50 text-brand' : 'border-border'}`}>{role}</button>)}<select value={status} onChange={event => setStatus(event.target.value as ProductStatus)} className="input ml-auto w-auto"><option>Activo</option><option>Inactivo</option></select></div></Section>
  const identification = <Section number="2" title="Identificación comercial" icon={Sparkles}><div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3"><label className="flex items-center gap-2 text-xs font-semibold text-emerald-900"><input type="checkbox" checked={automatic} onChange={event => { if (!event.target.checked) setManualName(generatedName); setAutomatic(event.target.checked) }} />Descripción automática</label>{automatic ? <p className="mt-2 text-sm font-semibold">{name}</p> : <Input className="mt-2" value={manualName} onChange={event => setManualName(event.target.value)} />}</div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Unidad de inventario *"><select value={unit} onChange={event => setUnit(event.target.value)} className="input"><option value="">Selecciona unidad</option>{units.filter(value => value.status === 'Activo').map(value => <option key={value.code}>{value.code}</option>)}</select></Field><Field label="Factor de conversión"><Input value={factor} onChange={event => setFactor(event.target.value)} /></Field><Field label="Stock mínimo"><Input value={minimum} onChange={event => setMinimum(event.target.value)} /></Field><Field label="Stock actual"><Input value={stock} onChange={event => setStock(event.target.value)} /></Field></div></Section>
  const specifications = <Section number="3" title="Especificaciones" icon={ClipboardList}>{attributes.length ? <div className="grid gap-4 md:grid-cols-3">{attributes.map(attribute => <Field key={attribute.id} label={`${attribute.name}${attribute.required ? ' *' : ''}`}><Input type={attribute.type === 'Numérico' ? 'number' : 'text'} value={values[attribute.id] ?? ''} onChange={event => setValues(current => ({ ...current, [attribute.id]: event.target.value }))} placeholder={attribute.suffix ? `En ${attribute.suffix}` : `Ingresa ${attribute.name.toLowerCase()}`} /><p className="mt-1 text-xs text-muted">{attribute.type}{attribute.suffix ? ` · ${attribute.suffix}` : ''}</p></Field>)}</div> : <p className="text-sm text-muted">No hay atributos configurados.</p>}</Section>
  const body = <div className={`space-y-4 ${presetSubcategoryId ? '[&_h2_span]:hidden' : ''}`}><div className="flex items-center gap-3 rounded-lg border border-blue-100 bg-[#f6f9ff] px-4 py-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-brand text-white"><Boxes className="h-4 w-4" /></span><div><p className="text-sm font-semibold">Registro rápido de catálogo</p><p className="text-xs text-muted">Completa los datos antes de registrar la compra.</p></div></div>{!presetSubcategoryId && classification}{presetSubcategoryId ? <>{specifications}{identification}</> : <>{identification}{specifications}</>}{error && <p className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div>
  if (floating) return <section className="absolute left-0 top-[calc(100%+12px)] z-50 w-[48rem] max-w-[calc(100vw-3rem)] rounded-xl border border-blue-200 bg-white p-4 shadow-panel before:absolute before:-top-2 before:left-10 before:h-4 before:w-4 before:rotate-45 before:border-l before:border-t before:border-blue-200 before:bg-white"><div className="relative flex items-start justify-between gap-4"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-50 text-brand"><SlidersHorizontal className="h-4 w-4" /></span><div><h4 className="text-sm font-semibold text-ink">Atributos del producto</h4><p className="text-xs text-muted">Completa las especificaciones de {fixedSubcategory?.name ?? 'este producto'}.</p></div></div><button type="button" onClick={onClose} className="rounded-md p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="Cerrar atributos"><X className="h-5 w-5" /></button></div><div className="relative mt-4 grid gap-3 sm:grid-cols-2">{attributes.map(attribute => <Field key={attribute.id} label={`${attribute.name}${attribute.required ? ' *' : ''}`}><Input type={attribute.type === 'Numérico' ? 'number' : 'text'} value={values[attribute.id] ?? ''} onChange={event => setValues(current => ({ ...current, [attribute.id]: event.target.value }))} placeholder={attribute.suffix ? `En ${attribute.suffix}` : `Ingresa ${attribute.name.toLowerCase()}`} /></Field>)}</div>{!attributes.length && <p className="relative mt-4 text-sm text-muted">Esta subcategoría no tiene atributos configurados.</p>}<div className="relative mt-4 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2.5"><p className="text-[11px] font-semibold text-emerald-800">DESCRIPCIÓN</p><p className="mt-0.5 text-sm font-semibold text-emerald-950">{name}</p></div>{error && <p className="relative mt-3 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<div className="relative mt-4 flex justify-end gap-2"><Button type="button" variant="outline" size="sm" onClick={onClose}>Cancelar</Button><Button type="button" size="sm" onClick={() => void save()}>{saveLabel}</Button></div></section>
  return <Dialog open wide title={item ? 'Editar producto' : 'Nuevo producto'} onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={() => void save()}>{saveLabel}</Button></>}><form onSubmit={event => { event.preventDefault(); void save() }}>{body}</form></Dialog>
}
function Section({ number, title, icon: Icon, children }: { number: string; title: string; icon: typeof Boxes; children: React.ReactNode }) { return <section className="rounded-xl border border-border bg-white p-5"><header className="mb-4 flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-50 text-brand"><Icon className="h-4 w-4" /></span><h2 className="text-[15px] font-semibold"><span className="mr-1.5 text-brand">{number}.</span>{title}</h2></header>{children}</section> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-700">{label}</span>{children}</label> }
