import { useMemo, useState, type ReactNode, type SelectHTMLAttributes } from 'react'
import { Calculator, ChevronRight, Diamond, Hexagon, Plus, Table2, Trash2 } from 'lucide-react'
import { Button } from '../../../components/ui/button'
import { Dialog } from '../../../components/ui/dialog'
import { Input } from '../../../components/ui/input'
import type { Attribute, ProductBase, ProductRole, ProductStatus, ProductVariant, Unit } from '../types/product.types'

type Presentation = { id: string; name: string; unit: string; minimum: number }
type SaveValue = { base: ProductBase; variants: ProductVariant[] }
const id = () => crypto.randomUUID()
const roles: { name: ProductRole; description: string; icon: typeof Table2 }[] = [
  { name: 'Mercadería', description: 'Se compra por compra nacional o importación.', icon: Table2 },
  { name: 'Insumo', description: 'Materia prima en la lista de materiales.', icon: Diamond },
  { name: 'Producto terminado', description: 'Nace solo de un proceso de producción.', icon: Hexagon },
]

export function ProductWizard({ item, units, onClose, onSave }: { item?: ProductBase; units: Unit[]; onClose: () => void; onSave: (value: SaveValue) => void | Promise<void> }) {
  const [pane, setPane] = useState(0)
  const [name, setName] = useState(item?.name ?? '')
  const [code, setCode] = useState(item?.code ?? `PROD-${String(Date.now()).slice(-3)}`)
  const [status, setStatus] = useState<ProductStatus>(item?.status ?? 'Activo')
  const [selected, setSelected] = useState<ProductRole[]>(item?.roles ?? [])
  const [type, setType] = useState<ProductBase['variantType']>(item?.variantType ?? 'Con variantes')
  const [immediate, setImmediate] = useState(item?.immediateConsumption ?? true)
  const [attributes, setAttributes] = useState<Attribute[]>(item?.attributes ?? [])
  const [draft, setDraft] = useState({ name: '', suffix: '', type: 'Numérico' as Attribute['type'], required: true, formula: false })
  const [presentations, setPresentations] = useState<Presentation[]>([{ id: id(), name: '', unit: units.find(unit => unit.status === 'Activo')?.code ?? 'UND', minimum: 0 }])
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  const steps = useMemo(() => type === 'Básico' ? [{ pane: 0, label: 'Datos' }, { pane: 2, label: 'Presentación' }, { pane: 3, label: 'Resumen' }] : [{ pane: 0, label: 'Datos' }, { pane: 1, label: 'Atributos' }, { pane: 2, label: 'Presentaciones' }, { pane: 3, label: 'Resumen' }], [type])
  const active = Math.max(0, steps.findIndex(step => step.pane === pane))
  const isSupply = selected.includes('Insumo')
  const unitsActive = units.filter(unit => unit.status === 'Activo')
  const changeType = (value: ProductBase['variantType']) => setType(value)
  const goNext = () => { if (pane === 0 && (!name.trim() || !selected.length)) { setError('Indica el nombre y al menos un rol para continuar.'); return } setError(''); if (active === steps.length - 1) return void save(); setPane(steps[active + 1].pane) }
  const save = async () => { const base: ProductBase = { id: item?.id ?? id(), code, name: name.trim(), status, roles: selected, variantType: type, immediateConsumption: isSupply ? immediate : false, attributes: type === 'Básico' ? [] : attributes }; const variants = presentations.filter(value => value.name.trim()).map((value, index) => ({ id: id(), baseId: base.id, code: `VAR-${String(Date.now()).slice(-4)}-${index + 1}`, values: {}, name: value.name, unit: value.unit, factor: 1, minimum: value.minimum, stock: 0, status })) satisfies ProductVariant[]; setSaving(true); try { await onSave({ base, variants }) } finally { setSaving(false) } }
  const addAttribute = () => { if (!draft.name.trim()) return; setAttributes(current => [...current, { id: id(), name: draft.name.trim(), suffix: draft.suffix, type: draft.type, required: draft.required, status: 'Activo', useInSubtotal: draft.type === 'Numérico' && draft.formula }]); setDraft({ name: '', suffix: '', type: 'Numérico', required: true, formula: false }) }
  const changePresentation = (presentationId: string, patch: Partial<Presentation>) => setPresentations(current => current.map(value => value.id === presentationId ? { ...value, ...patch } : value))

  return <Dialog open title={`Asistente · ${item ? 'Editar Producto' : 'Nuevo Producto'}`} onClose={onClose} wide footer={<><Button variant="outline" onClick={onClose} disabled={saving}>Cancelar</Button>{active > 0 && <Button variant="outline" onClick={() => setPane(steps[active - 1].pane)} disabled={saving}>Anterior</Button>}<Button onClick={goNext} disabled={saving}>{saving ? 'Guardando…' : active === steps.length - 1 ? 'Crear producto' : <>Siguiente <ChevronRight className="h-4 w-4" /></>}</Button></>}>
    <StepBar steps={steps} active={active} onSelect={index => index <= active && setPane(steps[index].pane)} />
    {pane === 0 && <section className="space-y-6"><SectionHeading number="1" title="Identificación" subtitle="Nombre, código y estado del producto." /><label><Label>Nombre del producto *</Label><Input value={name} onChange={event => setName(event.target.value)} placeholder="ej. Bobina de cartón" /></label><div className="grid gap-4 sm:grid-cols-2"><label><Label>Código</Label><Input value={code} onChange={event => setCode(event.target.value.toUpperCase())} /></label><label><Label>Estado</Label><Select value={status} onChange={event => setStatus(event.target.value as ProductStatus)}><option>Activo</option><option>Inactivo</option></Select></label></div><div className="border-t border-border pt-6"><SectionHeading number="2" title="Rol y tipo de producto" subtitle="Define cómo se usa en el sistema y si tendrá una o varias presentaciones." /><div className="grid gap-3 md:grid-cols-3">{roles.map(({ name: role, description, icon: Icon }) => <button type="button" key={role} onClick={() => setSelected(current => current.includes(role) ? current.filter(value => value !== role) : [...current, role])} className={`rounded-md border p-4 text-left transition ${selected.includes(role) ? 'border-brand bg-blue-50 ring-1 ring-brand' : 'border-border bg-[#f7f9fc]'}`}><span className="flex items-center justify-between text-sm font-semibold"><span className="flex items-center gap-2"><Icon className="h-4 w-4 text-brand" />{role}</span><span className={`flex h-5 w-5 items-center justify-center rounded border ${selected.includes(role) ? 'border-brand bg-brand text-white' : 'border-slate-400 bg-white'}`}>{selected.includes(role) ? '✓' : ''}</span></span><small className="mt-3 block min-h-10 text-xs leading-5 text-muted">{description}</small></button>)}</div>{isSupply && <label className="mt-3 block cursor-pointer border-b border-dashed border-border pb-4"><span className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.4px] text-slate-600"><input type="checkbox" className="h-5 w-5 accent-blue-600" checked={immediate} onChange={event => setImmediate(event.target.checked)} />Consumo inmediato</span><span className="mt-1 block text-xs text-muted">Se descuenta del stock al confirmar la orden. Desmarca solo si este insumo se comparte entre varias órdenes (ej. bobinas).</span></label>}<div className="mt-4 flex flex-wrap items-center gap-3"><Label>Tipo de producto</Label><div className="rounded-full border border-border bg-[#f3f6fa] p-1"><button type="button" onClick={() => changeType('Con variantes')} className={`rounded-full px-4 py-2 text-xs font-semibold ${type === 'Con variantes' ? 'bg-brand text-white' : 'text-muted'}`}>Con variantes</button><button type="button" onClick={() => changeType('Básico')} className={`rounded-full px-4 py-2 text-xs font-semibold ${type === 'Básico' ? 'bg-brand text-white' : 'text-muted'}`}>Básico</button></div></div></div>{error && <p className="text-xs font-medium text-red-600">{error}</p>}</section>}
    {pane === 1 && <section><SectionHeading number="3" title="Atributos de las presentaciones" subtitle={isSupply && selected.length === 1 ? 'Los insumos no suelen necesitar atributos. Puedes continuar sin agregar ninguno.' : 'Define las características que distinguirán a cada presentación.'} /><div className="grid gap-3 rounded-md border border-border bg-[#f7f9fc] p-3 sm:grid-cols-2"><label><Label>Nombre del atributo *</Label><Input value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })} placeholder="ej. Gramaje, Largo" /></label><label><Label>Acrónimo (opcional)</Label><Input value={draft.suffix} onChange={event => setDraft({ ...draft, suffix: event.target.value })} placeholder="ej. cm, kg, gr" /></label><label><Label>Tipo de campo</Label><Select value={draft.type} onChange={event => setDraft({ ...draft, type: event.target.value as Attribute['type'] })}><option>Numérico</option><option>Texto</option></Select></label><label><Label>Requerido</Label><Select value={draft.required ? 'yes' : 'no'} onChange={event => setDraft({ ...draft, required: event.target.value === 'yes' })}><option value="yes">Obligatorio</option><option value="no">Opcional</option></Select></label>{draft.type === 'Numérico' && <label className="sm:col-span-2 rounded-md border border-blue-200 bg-blue-50 p-3 text-xs text-slate-600"><span className="flex items-center gap-2 font-semibold text-slate-700"><input type="checkbox" className="accent-blue-600" checked={draft.formula} onChange={event => setDraft({ ...draft, formula: event.target.checked })} /><Calculator className="h-4 w-4 text-brand" />Usar este atributo en el cálculo del subtotal</span><span className="mt-2 block">Subtotal de compra/importación = valor del atributo × costo unitario.</span></label>}<Button type="button" variant="outline" className="sm:col-span-2" onClick={addAttribute}><Plus className="h-4 w-4" />Agregar atributo</Button></div><div className="mt-4 divide-y divide-border rounded-md border border-border">{attributes.length ? attributes.map(attribute => <div className="flex items-center gap-3 px-4 py-3 text-sm" key={attribute.id}><span className="flex-1 font-medium">{attribute.name}</span><span className="text-xs text-muted">{attribute.type}{attribute.suffix && ` · ${attribute.suffix}`}{attribute.useInSubtotal && ' · Subtotal'}</span><button type="button" onClick={() => setAttributes(current => current.filter(value => value.id !== attribute.id))} className="text-red-600"><Trash2 className="h-4 w-4" /></button></div>) : <p className="px-4 py-7 text-center text-sm text-muted">Aún no agregaste atributos.</p>}</div></section>}
    {pane === 2 && <section><SectionHeading number={type === 'Básico' ? '2' : '4'} title={type === 'Básico' ? 'Presentación básica' : 'Presentaciones'} subtitle={type === 'Básico' ? 'Registra la única presentación que se controlará en inventario.' : 'Registra las unidades que se controlarán en inventario.'} /><div className="space-y-3">{presentations.map((presentation, index) => <div className="grid gap-3 rounded-md border border-border p-3 sm:grid-cols-[1fr_150px_120px_auto]" key={presentation.id}><Input placeholder={`Presentación ${index + 1}`} value={presentation.name} onChange={event => changePresentation(presentation.id, { name: event.target.value })} /><Select value={presentation.unit} onChange={event => changePresentation(presentation.id, { unit: event.target.value })}>{unitsActive.map(unit => <option key={unit.id} value={unit.code}>{unit.code}</option>)}</Select><Input type="number" min="0" value={presentation.minimum} onChange={event => changePresentation(presentation.id, { minimum: Number(event.target.value) })} /><button type="button" disabled={presentations.length === 1} onClick={() => setPresentations(current => current.filter(value => value.id !== presentation.id))} className="rounded border border-red-200 bg-red-50 text-red-600 disabled:opacity-40"><Trash2 className="mx-auto h-4 w-4" /></button></div>)}{type === 'Con variantes' && <Button type="button" variant="outline" onClick={() => setPresentations(current => [...current, { id: id(), name: '', unit: unitsActive[0]?.code ?? 'UND', minimum: 0 }])}><Plus className="h-4 w-4" />Agregar presentación</Button>}</div></section>}
    {pane === 3 && <section><SectionHeading number={String(steps.length)} title="Resumen" subtitle="Revisa la información antes de guardar." /><dl className="grid gap-4 rounded-md border border-border bg-[#f7f9fc] p-4 text-sm sm:grid-cols-2"><Summary label="Producto" value={name || 'Sin nombre'} /><Summary label="Código" value={code} /><Summary label="Roles" value={selected.join(', ') || 'Sin seleccionar'} /><Summary label="Tipo" value={type} />{isSupply && <Summary label="Consumo inmediato" value={immediate ? 'Sí' : 'No'} />}<Summary label="Atributos" value={attributes.map(attribute => attribute.name).join(', ') || 'Ninguno'} /><Summary label="Presentaciones" value={String(presentations.filter(value => value.name.trim()).length)} /></dl></section>}
  </Dialog>
}

function StepBar({ steps, active, onSelect }: { steps: { pane: number; label: string }[]; active: number; onSelect: (index: number) => void }) { return <nav className="mb-7 flex items-center border-b border-border pb-5">{steps.map((step, index) => <div key={step.label} className="flex min-w-0 flex-1 items-center"><button type="button" onClick={() => onSelect(index)} className={`flex shrink-0 items-center gap-2 text-xs font-semibold ${index === active ? 'text-brand' : index < active ? 'text-slate-700' : 'text-muted'}`}><span className={`flex h-9 w-9 items-center justify-center rounded-full border ${index === active ? 'border-brand bg-brand text-white' : 'border-[#cbd7ea] bg-white'}`}>{index < active ? '✓' : index + 1}</span><span className="hidden md:inline">{step.label}</span></button>{index < steps.length - 1 && <span className={`mx-3 h-px min-w-3 flex-1 ${index < active ? 'bg-brand' : 'bg-[#d8e1ef]'}`} />}</div>)}</nav> }
function Label({ children }: { children: ReactNode }) { return <span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-[.4px] text-slate-600">{children}</span> }
function SectionHeading({ number, title, subtitle }: { number: string; title: string; subtitle: string }) { return <div className="mb-4 flex gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-brand text-sm font-bold text-white">{number}</span><div><h3 className="text-base font-semibold">{title}</h3><p className="text-xs text-muted">{subtitle}</p></div></div> }
function Select({ children, ...props }: SelectHTMLAttributes<HTMLSelectElement>) { return <select className="h-10 w-full rounded-md border border-border bg-[#f4f7fb] px-3 text-sm outline-none focus:border-brand focus:bg-white focus:ring-1 focus:ring-brand" {...props}>{children}</select> }
function Summary({ label, value }: { label: string; value: string }) { return <div><dt className="text-[11px] font-semibold uppercase tracking-[.4px] text-muted">{label}</dt><dd className="mt-1 font-medium text-slate-700">{value}</dd></div> }
