import { ImportStatus, InventoryMovementType, Prisma, PrismaClient, ProductRoleType, ProductStatus, ProductVariantType, ProductionMaterialStatus, ProductionStatus, PurchaseStatus, SupplierType, UserStatus } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()
const d = (value: number) => new Prisma.Decimal(value)

type PresentationSeed = { code: string; name: string; unit: string; factor: number; minimum: number; stock: number }
type ProductSeed = { code: string; name: string; category: string; roles: ProductRoleType[]; presentations: PresentationSeed[]; immediateConsumption?: boolean }

// Catálogo de demostración para una planta de empaques y cajas de cartón.
const products: ProductSeed[] = [
  { code: 'PROD-002', name: 'Bobina de plástico', category: 'Materiales de embalaje', roles: [ProductRoleType.MERCHANDISE], presentations: [{ code: '001', name: 'Bobina de plástico 100x80 120g 50mic', unit: 'KG', factor: 1, minimum: 100, stock: 350 }] },
  { code: 'PROD-003', name: 'Papel couché', category: 'Papeles e insumos', roles: [ProductRoleType.MERCHANDISE, ProductRoleType.SUPPLY], presentations: [{ code: '002', name: 'Papel couché 150cm 90g', unit: 'RESMA', factor: 1, minimum: 50, stock: 45 }] },
  { code: 'PROD-004', name: 'Placa offset', category: 'Preprensa e impresión', roles: [ProductRoleType.SUPPLY, ProductRoleType.FINISHED_PRODUCT], presentations: [{ code: '003', name: 'Placa offset', unit: 'UND', factor: 1, minimum: 200, stock: 172 }] },
  { code: 'PROD-005', name: 'Tintas para offset', category: 'Preprensa e impresión', roles: [ProductRoleType.MERCHANDISE, ProductRoleType.SUPPLY], presentations: [{ code: '004', name: 'Tinta offset negro 1kg', unit: 'KG', factor: 1, minimum: 20, stock: 12 }, { code: '004-C', name: 'Tinta offset cyan 1kg', unit: 'KG', factor: 1, minimum: 10, stock: 8 }] },
  { code: 'PROD-006', name: 'Cinta de embalaje', category: 'Materiales de embalaje', roles: [ProductRoleType.MERCHANDISE], presentations: [{ code: '005', name: 'Cinta de embalaje', unit: 'CAJA', factor: 6, minimum: 10, stock: 1 }] },
  { code: 'PROD-007', name: 'Bobina de papel', category: 'Papeles e insumos', roles: [ProductRoleType.MERCHANDISE, ProductRoleType.SUPPLY], presentations: [{ code: '006', name: 'Bobina de papel 150x120 650kg', unit: 'ROLLO', factor: 1, minimum: 1, stock: 4 }, { code: '007', name: 'Bobina de papel 100x100 500kg', unit: 'ROLLO', factor: 1, minimum: 0, stock: 1 }, { code: '009', name: 'Bobina de papel 120 150kg', unit: 'ROLLO', factor: 1, minimum: 0, stock: 1 }] },
  { code: 'PROD-008', name: 'Balde de plástico', category: 'Preprensa e impresión', roles: [ProductRoleType.SUPPLY], presentations: [{ code: '008', name: 'Balde de plástico', unit: 'UND', factor: 1, minimum: 0, stock: 5 }] },
  { code: 'PROD-009', name: 'Bobina de Cartón Estucado', category: 'Cartón y bobinas', roles: [ProductRoleType.MERCHANDISE, ProductRoleType.SUPPLY], presentations: [{ code: '010', name: 'Bobina de Cartón Estucado 249G 122.8CM 1691KG 26020521', unit: 'UND', factor: 1, minimum: 1, stock: 8 }, { code: '011', name: 'Bobina de Cartón Estucado 250G 104CM 858KG 26031022', unit: 'UND', factor: 1, minimum: 1, stock: 6 }] },
  { code: 'PROD-010', name: 'Placa', category: 'Preprensa e impresión', roles: [ProductRoleType.MERCHANDISE, ProductRoleType.SUPPLY], presentations: [{ code: '012', name: 'Placa 12cm', unit: 'ROLLO', factor: 1, minimum: 2, stock: 2 }] },
  { code: 'PROD-011', name: 'Papel adhesivo P3 de 100cm x 70cm', category: 'Materiales de embalaje', roles: [ProductRoleType.MERCHANDISE], presentations: [{ code: '013', name: 'Papel adhesivo P3 de 100cm x 70cm', unit: 'PALETA', factor: 60, minimum: 10, stock: 10 }] },
  { code: 'PROD-012', name: 'Papel adhesivo P3 de 100cm x 70cm, paquete x 100 hojas', category: 'Materiales de embalaje', roles: [ProductRoleType.MERCHANDISE], presentations: [{ code: '014', name: 'Papel adhesivo P3 de 100cm x 70cm, paquete x 100 hojas', unit: 'PAQUETE', factor: 1, minimum: 10, stock: 10 }] },
  { code: 'PROD-013', name: 'Placas CTCP', category: 'Preprensa e impresión', roles: [ProductRoleType.MERCHANDISE, ProductRoleType.SUPPLY, ProductRoleType.FINISHED_PRODUCT], presentations: [{ code: '015', name: 'Placas CTCP 650x550', unit: 'CAJA50', factor: 1, minimum: 10, stock: 10 }, { code: '016', name: 'Placas CTCP 510x400', unit: 'CAJA100', factor: 1, minimum: 10, stock: 8 }, { code: '017', name: 'Placas CTCP 525x459', unit: 'CAJA100', factor: 1, minimum: 10, stock: 6 }] },
  { code: 'PROD-014', name: 'Cartón corrugado microcanal', category: 'Cartón y bobinas', roles: [ProductRoleType.SUPPLY], presentations: [{ code: '018', name: 'Plancha de cartón corrugado 1.20 x 2.40 m', unit: 'PLANCHA', factor: 1, minimum: 500, stock: 420 }] },
  { code: 'PROD-015', name: 'Barniz UV', category: 'Preprensa e impresión', roles: [ProductRoleType.SUPPLY], presentations: [{ code: '019', name: 'Barniz UV alto brillo 20kg', unit: 'KG', factor: 1, minimum: 20, stock: 32 }] },
  { code: 'PROD-016', name: 'Troquel para caja', category: 'Producción', roles: [ProductRoleType.SUPPLY], presentations: [{ code: '020', name: 'Troquel caja microcorrugada 30x20x10 cm', unit: 'UND', factor: 1, minimum: 1, stock: 2 }] },
  { code: 'PROD-017', name: 'Caja microcorrugada impresa', category: 'Productos terminados', roles: [ProductRoleType.FINISHED_PRODUCT], immediateConsumption: false, presentations: [{ code: '021', name: 'Caja microcorrugada impresa 30x20x10 cm', unit: 'UND', factor: 1, minimum: 300, stock: 250 }] },
]

async function main() {
  const company = await prisma.company.upsert({ where: { taxId: 'DEMO-EUROPLATE' }, update: { name: 'Europlate Empaques S.A.C.', currency: 'PEN' }, create: { name: 'Europlate Empaques S.A.C.', taxId: 'DEMO-EUROPLATE', currency: 'PEN' } })
  await prisma.role.createMany({ data: [{ key: 'admin', name: 'Administrador' }, { key: 'vendedor', name: 'Vendedor' }, { key: 'operador', name: 'Operador' }], skipDuplicates: true })
  await prisma.permission.createMany({ data: ['products', 'suppliers', 'purchases', 'imports', 'inventory', 'production', 'users', 'dashboard'].flatMap((module) => [{ key: `${module}.read`, module, action: 'read' }, { key: `${module}.manage`, module, action: 'manage' }]), skipDuplicates: true })
  const adminRole = await prisma.role.findUniqueOrThrow({ where: { key: 'admin' } })
  await prisma.rolePermission.createMany({ data: (await prisma.permission.findMany()).map((permission) => ({ roleId: adminRole.id, permissionId: permission.id })), skipDuplicates: true })

  const unitDefinitions = [['UND', 'Unidad'], ['KG', 'Kilogramo'], ['RESMA', 'Resma'], ['CAJA', 'Caja'], ['ROLLO', 'Rollo'], ['PLANCHA', 'Plancha'], ['PALETA', 'Paleta'], ['PAQUETE', 'Paquete'], ['CAJA50', 'Caja x 50'], ['CAJA100', 'Caja x 100']] as const
  await prisma.unit.createMany({ data: unitDefinitions.map(([code, description]) => ({ code, description, status: ProductStatus.ACTIVE })), skipDuplicates: true })
  const unitMap = new Map((await prisma.unit.findMany({ where: { code: { in: unitDefinitions.map(([code]) => code) } } })).map((unit) => [unit.code, unit]))
  const passwordHash = await bcrypt.hash('Europlate123!', 12)
  const admin = await prisma.user.upsert({ where: { email: 'admin@europlate.pe' }, update: { companyId: company.id, name: 'Administrador Demo', passwordHash, status: UserStatus.ACTIVE }, create: { companyId: company.id, name: 'Administrador Demo', email: 'admin@europlate.pe', passwordHash, status: UserStatus.ACTIVE } })
  await prisma.userRole.upsert({ where: { userId_roleId: { userId: admin.id, roleId: adminRole.id } }, update: {}, create: { userId: admin.id, roleId: adminRole.id } })

  const warehouses = new Map<string, { id: string }>()
  for (const name of ['Almacén Principal', 'Almacén Producción', 'Almacén Trujillo']) warehouses.set(name, await prisma.warehouse.upsert({ where: { companyId_name: { companyId: company.id, name } }, update: { status: ProductStatus.ACTIVE }, create: { companyId: company.id, name, status: ProductStatus.ACTIVE } }))
  const principal = warehouses.get('Almacén Principal')!
  const productionWarehouse = warehouses.get('Almacén Producción')!
  const categoryMap = new Map<string, { id: string }>(); const productMap = new Map<string, { id: string }>(); const presentationMap = new Map<string, { id: string }>()
  for (const seed of products) {
    let category = categoryMap.get(seed.category)
    if (!category) { category = await prisma.category.upsert({ where: { name: seed.category }, update: {}, create: { name: seed.category } }); categoryMap.set(seed.category, category) }
    const product = await prisma.product.upsert({ where: { code: seed.code }, update: { name: seed.name, categoryId: category.id, roles: seed.roles, status: ProductStatus.ACTIVE, variantType: seed.presentations.length > 1 ? ProductVariantType.WITH_VARIANTS : ProductVariantType.BASIC, immediateConsumption: seed.immediateConsumption ?? true }, create: { code: seed.code, name: seed.name, categoryId: category.id, roles: seed.roles, status: ProductStatus.ACTIVE, variantType: seed.presentations.length > 1 ? ProductVariantType.WITH_VARIANTS : ProductVariantType.BASIC, immediateConsumption: seed.immediateConsumption ?? true } })
    productMap.set(seed.code, product)
    for (const p of seed.presentations) {
      const unit = unitMap.get(p.unit); if (!unit) throw new Error(`Unidad no encontrada: ${p.unit}`)
      const presentation = await prisma.productPresentation.upsert({ where: { code: p.code }, update: { productId: product.id, unitId: unit.id, name: p.name, factor: d(p.factor), minimumStock: d(p.minimum), currentStock: d(p.stock), status: ProductStatus.ACTIVE }, create: { code: p.code, productId: product.id, unitId: unit.id, name: p.name, factor: d(p.factor), minimumStock: d(p.minimum), currentStock: d(p.stock), status: ProductStatus.ACTIVE } })
      presentationMap.set(p.code, presentation)
      const warehouse = seed.code === 'PROD-017' ? productionWarehouse : principal
      await prisma.stock.upsert({ where: { productId_warehouseId: { productId: product.id, warehouseId: warehouse.id } }, update: { quantity: d(p.stock) }, create: { productId: product.id, warehouseId: warehouse.id, quantity: d(p.stock) } })
    }
  }

  const supplierSeeds = [{ name: 'Cartones del Perú S.A.C.', taxId: '20609876543', email: 'ventas@cartonesperu.pe', phone: '01-7001200', type: SupplierType.NATIONAL }, { name: 'Química Gráfica Andina S.A.C.', taxId: '20512345678', email: 'comercial@quimicagrafica.pe', phone: '01-4457889', type: SupplierType.NATIONAL }, { name: 'Shenzhen Paper Co. Ltd.', taxId: '91234567890', email: 'export@shenzhenpaper.cn', phone: '+86-755-2233445', type: SupplierType.FOREIGN }, { name: 'SILVANIA RESOURCES, INC.', taxId: '22-3096554', email: 'orders@silvaniaresources.com', phone: '+1-305-555-0188', type: SupplierType.FOREIGN }]
  const suppliers = new Map<string, { id: string }>()
  for (const seed of supplierSeeds) suppliers.set(seed.name, await prisma.supplier.upsert({ where: { id: `seed-${seed.taxId}` }, update: seed, create: { id: `seed-${seed.taxId}`, companyId: company.id, ...seed, status: ProductStatus.ACTIVE } }))
  const agent = await prisma.customsAgent.upsert({ where: { companyId_ruc: { companyId: company.id, ruc: '20501234567' } }, update: { name: 'Aduanas Callao S.A.C.', contactName: 'María Ríos', phone: '01-4567890', email: 'operaciones@aduanascallao.pe', status: ProductStatus.ACTIVE }, create: { companyId: company.id, name: 'Aduanas Callao S.A.C.', ruc: '20501234567', contactName: 'María Ríos', phone: '01-4567890', email: 'operaciones@aduanascallao.pe', status: ProductStatus.ACTIVE } })
  const purchaseItem = (code: string, presentation: string, quantity: number, unitPrice: number) => ({ productId: productMap.get(code)!.id, presentationId: presentationMap.get(presentation)!.id, warehouseId: principal.id, quantity: d(quantity), unitPrice: d(unitPrice) })
  await prisma.purchase.upsert({ where: { number: 'OC-2026-000128' }, update: {}, create: { companyId: company.id, supplierId: suppliers.get('Cartones del Perú S.A.C.')!.id, number: 'OC-2026-000128', supplierInvoiceNumber: 'F001-000123', status: PurchaseStatus.RECEIVED, currency: 'PEN', purchaseDate: new Date('2026-08-20'), receiptDate: new Date('2026-08-20'), total: d(4280), items: { create: [purchaseItem('PROD-014', '018', 400, 8.5), purchaseItem('PROD-006', '005', 10, 88)] }, documents: { create: { fileName: 'F001-000123.pdf', mimeType: 'application/pdf', storageKey: 'seed/purchases/F001-000123.pdf' } } } })
  await prisma.purchase.upsert({ where: { number: 'OC-2026-000129' }, update: {}, create: { companyId: company.id, supplierId: suppliers.get('Química Gráfica Andina S.A.C.')!.id, number: 'OC-2026-000129', supplierInvoiceNumber: 'F002-000847', status: PurchaseStatus.APPROVED, currency: 'USD', purchaseDate: new Date('2026-08-23'), receiptDate: new Date('2026-08-24'), total: d(840), items: { create: [purchaseItem('PROD-005', '004', 20, 22), purchaseItem('PROD-015', '019', 20, 20)] } } })
  const importItem = (code: string, presentation: string, quantity: number, unitCostUsd: number) => ({ productId: productMap.get(code)!.id, presentationId: presentationMap.get(presentation)!.id, warehouseId: principal.id, quantity: d(quantity), unitCostUsd: d(unitCostUsd) })
  await prisma.import.upsert({ where: { number: 'IMP-2026-001' }, update: {}, create: { companyId: company.id, supplierId: suppliers.get('Shenzhen Paper Co. Ltd.')!.id, customsAgentId: agent.id, number: 'IMP-2026-001', containerNumber: 'SZPA123456', duaNumber: '118-2026-10-000001', purchaseOrderNumber: 'OCI-2026-001', countryOfOrigin: 'China', status: ImportStatus.RECEIVED, currency: 'USD', arrivalDate: new Date('2026-08-21'), customsCostUsd: d(120), customsCostPen: d(450), totalUsd: d(892.5), items: { create: [importItem('PROD-009', '010', 4, 150), importItem('PROD-013', '015', 5, 58.5)] }, documents: { create: { fileName: 'DUA-118-2026-10-000001.pdf', mimeType: 'application/pdf', linkUrl: 'https://example.com/documents/dua-seed.pdf' } } } })
  await prisma.productionOrder.upsert({ where: { number: 'OP-000045' }, update: {}, create: { number: 'OP-000045', companyId: company.id, productId: productMap.get('PROD-017')!.id, presentationId: presentationMap.get('021')!.id, warehouseId: productionWarehouse.id, quantity: d(300), scheduledAt: new Date('2026-08-24'), status: ProductionStatus.IN_PROGRESS, note: 'Producción de cajas microcorrugadas para cliente mayorista.', materials: { create: [{ productId: productMap.get('PROD-014')!.id, presentationId: presentationMap.get('018')!.id, warehouseId: principal.id, quantity: d(300), status: ProductionMaterialStatus.RESERVED, immediateConsumption: true }, { productId: productMap.get('PROD-005')!.id, presentationId: presentationMap.get('004')!.id, warehouseId: principal.id, quantity: d(12), status: ProductionMaterialStatus.RESERVED, immediateConsumption: true }, { productId: productMap.get('PROD-013')!.id, presentationId: presentationMap.get('015')!.id, warehouseId: principal.id, quantity: d(2), status: ProductionMaterialStatus.RESERVED, immediateConsumption: false }] } } })
  await prisma.inventoryMovement.deleteMany({ where: { reference: { startsWith: 'SEED-' } } })
  await prisma.inventoryMovement.createMany({ data: [{ productId: productMap.get('PROD-014')!.id, presentationId: presentationMap.get('018')!.id, warehouseId: principal.id, createdByUserId: admin.id, type: InventoryMovementType.PURCHASE_RECEIPT, quantity: d(400), reference: 'SEED-OC-2026-000128', note: 'Recepción inicial de cartón corrugado.' }, { productId: productMap.get('PROD-009')!.id, presentationId: presentationMap.get('010')!.id, warehouseId: principal.id, createdByUserId: admin.id, type: InventoryMovementType.IMPORT_RECEIPT, quantity: d(4), reference: 'SEED-IMP-2026-001', note: 'Recepción de bobinas importadas.' }, { productId: productMap.get('PROD-014')!.id, presentationId: presentationMap.get('018')!.id, warehouseId: productionWarehouse.id, createdByUserId: admin.id, type: InventoryMovementType.TRANSFER_IN, quantity: d(300), reference: 'SEED-OP-000045', note: 'Material reservado para producción.' }] })
  await prisma.exchangeRate.upsert({ where: { companyId_effectiveDate: { companyId: company.id, effectiveDate: new Date('2026-08-27') } }, update: { value: d(3.78), source: 'SBS', note: 'Tipo de cambio referencial de demo', createdByUserId: admin.id }, create: { companyId: company.id, createdByUserId: admin.id, effectiveDate: new Date('2026-08-27'), value: d(3.78), source: 'SBS', note: 'Tipo de cambio referencial de demo' } })
  console.log(`Seed completado: ${products.length} productos, ${supplierSeeds.length} proveedores, 2 compras, 1 importación y 1 orden de producción.`)
}

main().catch((error) => { console.error(error); process.exitCode = 1 }).finally(() => prisma.$disconnect())
