import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Pencil, Plus, RefreshCw, Trash2 } from 'lucide-react'
import { Button } from '../../../components/ui/button'
import { Dialog } from '../../../components/ui/dialog'
import { Input } from '../../../components/ui/input'
import { createExchangeRate, deleteExchangeRate, listExchangeRates, refreshExchangeRate, type ExchangeRate, type ExchangeRatePayload, updateExchangeRate } from '../services/exchange-rate-api.service'

const amount = (rate: ExchangeRate) => Number(rate.value)
const date = (rate: ExchangeRate) => rate.effectiveDate.slice(0, 10)
const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-[.4px] text-slate-600">{label}</span>{children}</label>
export function SettingsPage() {
  const client = useQueryClient(); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<ExchangeRate>(); const [notice, setNotice] = useState(''); const query = useQuery({ queryKey: ['exchange-rates'], queryFn: listExchangeRates }); const rates = query.data ?? []; const current = rates[0]
  const invalidate = () => { void client.invalidateQueries({ queryKey: ['exchange-rates'] }) }; const say = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(''), 3500) }
  const save = useMutation({ mutationFn: ({ id, payload }: { id?: string; payload: ExchangeRatePayload }) => id ? updateExchangeRate(id, payload) : createExchangeRate(payload), onSuccess: () => { invalidate(); setModal(false); say('Tipo de cambio guardado correctamente.') }, onError: (error: Error) => say(error.message) })
  const automatic = useMutation({ mutationFn: refreshExchangeRate, onSuccess: rate => { invalidate(); say(`Tasa actualizada: S/ ${amount(rate).toFixed(4)} por USD.`) }, onError: (error: Error) => say(error.message) })
  const remove = useMutation({ mutationFn: deleteExchangeRate, onSuccess: () => { invalidate(); say('Tipo de cambio eliminado.') }, onError: (error: Error) => say(error.message) })
  return <div className="mx-auto max-w-7xl"><section className="rounded-[10px] border border-border bg-white p-5 shadow-card"><header className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-sm font-semibold">Tipo de Cambio USD ↔ S/</h1><div className="flex gap-2"><Button size="sm" variant="outline" disabled={automatic.isPending} onClick={() => automatic.mutate()}><RefreshCw className={`h-4 w-4 ${automatic.isPending ? 'animate-spin' : ''}`}/>Actualizar desde API</Button><Button size="sm" onClick={() => { setEditing(undefined); setModal(true) }}><Plus className="h-4 w-4"/>Nuevo Tipo de Cambio</Button></div></header><div className="py-4">{current ? <div className="inline-flex items-baseline gap-3.5 rounded-lg border border-blue-300 bg-[linear-gradient(135deg,#dbeafe_0%,#dcfce7_100%)] px-5 py-3.5"><span className="text-xs font-semibold uppercase tracking-[.5px] text-slate-600">TC Vigente</span><strong className="font-mono text-2xl text-brand">S/ {amount(current).toFixed(4)}</strong><span className="text-xs text-muted">por USD</span></div> : <p className="text-sm text-muted">Aún no hay un tipo de cambio registrado.</p>}<p className="mt-2 text-[11px] text-muted">La actualización consulta USD → PEN desde el servidor. Compras e importaciones nuevas usan la tasa vigente; las anteriores conservan su valor histórico.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="bg-[#f7f9fc] text-[11px] uppercase tracking-[.5px] text-muted">{['Fecha', 'Valor', 'Usuario', 'Origen / observación', ''].map(value => <th className="border-y border-border px-4 py-2.5" key={value}>{value}</th>)}</tr></thead><tbody>{query.isLoading ? <tr><td colSpan={5} className="p-8 text-center text-sm text-muted">Cargando tipos de cambio…</td></tr> : rates.map(rate => <tr key={rate.id} className="border-b border-border text-[13px]"><td className="px-4 py-3">{date(rate)}</td><td className="px-4 py-3 font-mono font-bold text-brand">S/ {amount(rate).toFixed(4)}</td><td className="px-4 py-3 text-xs text-slate-600">{rate.createdBy?.email ?? 'Sistema'}</td><td className="px-4 py-3 text-slate-600">{rate.source ?? 'Manual'}{rate.note && ` · ${rate.note}`}</td><td className="px-4 py-3 text-right"><Mini onClick={() => { setEditing(rate); setModal(true) }}><Pencil className="h-3.5 w-3.5"/></Mini><Mini danger onClick={() => { if (window.confirm('¿Eliminar este tipo de cambio?')) remove.mutate(rate.id) }}><Trash2 className="h-3.5 w-3.5"/></Mini></td></tr>)}</tbody></table></div></section>{modal && <RateDialog item={editing} saving={save.isPending} onClose={() => setModal(false)} onSave={payload => save.mutate({ id: editing?.id, payload })}/>} {notice && <div className="fixed bottom-6 right-6 z-[60] rounded-md border border-border border-l-4 border-l-emerald-600 bg-white px-4 py-3 text-sm shadow-panel">{notice}</div>}</div>
}
function RateDialog({ item, saving, onClose, onSave }: { item?: ExchangeRate; saving: boolean; onClose: () => void; onSave: (payload: ExchangeRatePayload) => void }) { const [effectiveDate, setDate] = useState(item ? date(item) : new Date().toISOString().slice(0, 10)); const [value, setValue] = useState(item ? amount(item) : 0); const [note, setNote] = useState(item?.note ?? ''); return <Dialog open title={item ? 'Editar tipo de cambio' : 'Nuevo tipo de cambio'} onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>Cancelar</Button><Button form="rate-form" type="submit" disabled={saving}>Guardar</Button></>}><form id="rate-form" className="space-y-4" onSubmit={(event: FormEvent) => { event.preventDefault(); onSave({ effectiveDate, value, source: item?.source ?? 'Manual', note }) }}><Field label="Fecha *"><Input type="date" required value={effectiveDate} onChange={event => setDate(event.target.value)}/></Field><Field label="Valor (S/ por USD) *"><Input type="number" required min="0.0001" step="0.0001" value={value || ''} onChange={event => setValue(Number(event.target.value))} placeholder="ej. 3.7850"/></Field><Field label="Observación"><textarea value={note} onChange={event => setNote(event.target.value)} placeholder="ej. SBS, BCR, etc." className="min-h-20 w-full rounded-md border border-border bg-[#f4f7fb] p-3 text-sm outline-none focus:border-brand"/></Field></form></Dialog> }
function Mini({ children, danger, onClick }: { children: React.ReactNode; danger?: boolean; onClick: () => void }) { return <button onClick={onClick} className={`ml-1 inline-flex h-7 w-7 items-center justify-center rounded border ${danger ? 'border-red-200 bg-red-50 text-red-600' : 'border-border bg-white text-slate-600'}`}>{children}</button> }
