import { api } from '../../../lib/api-client'
import type { Attribute, ProductBase, ProductRole, ProductStatus, ProductVariant, Unit } from '../types/product.types'

type ApiProduct = { id: string; code: string; name: string; status: 'ACTIVE' | 'INACTIVE'; roles: ('MERCHANDISE' | 'SUPPLY' | 'FINISHED_PRODUCT')[]; variantType: 'WITH_VARIANTS' | 'BASIC'; immediateConsumption: boolean; attributes: { id: string; name: string; dataType: 'TEXT' | 'NUMBER'; required: boolean; suffix: string | null; status: 'ACTIVE' | 'INACTIVE'; useInSubtotal: boolean }[]; presentations: { id: string; code: string; name: string; factor: string | number; minimumStock: string | number; currentStock: string | number; status: 'ACTIVE' | 'INACTIVE'; unit: { code: string } }[] }
type ApiUnit = { id: string; code: string; description: string; status: 'ACTIVE' | 'INACTIVE' }
const toRole: Record<ApiProduct['roles'][number], ProductRole> = { MERCHANDISE: 'Mercadería', SUPPLY: 'Insumo', FINISHED_PRODUCT: 'Producto terminado' }
const fromRole: Record<ProductRole, ApiProduct['roles'][number]> = { Mercadería: 'MERCHANDISE', Insumo: 'SUPPLY', 'Producto terminado': 'FINISHED_PRODUCT' }
const toStatus = (status: 'ACTIVE' | 'INACTIVE'): ProductStatus => status === 'ACTIVE' ? 'Activo' : 'Inactivo'
const fromStatus = (status: ProductStatus) => status === 'Activo' ? 'ACTIVE' : 'INACTIVE'

export const mapProduct = (product: ApiProduct): { base: ProductBase; variants: ProductVariant[] } => ({ base: { id: product.id, code: product.code, name: product.name, status: toStatus(product.status), roles: product.roles.map(role => toRole[role]), variantType: product.variantType === 'WITH_VARIANTS' ? 'Con variantes' : 'Básico', immediateConsumption: product.immediateConsumption, attributes: product.attributes.map(attribute => ({ id: attribute.id, name: attribute.name, type: attribute.dataType === 'NUMBER' ? 'Numérico' : 'Texto', required: attribute.required, suffix: attribute.suffix ?? '', status: toStatus(attribute.status), useInSubtotal: attribute.useInSubtotal })) }, variants: product.presentations.map(presentation => ({ id: presentation.id, baseId: product.id, code: presentation.code, values: {}, name: presentation.name, unit: presentation.unit.code, factor: Number(presentation.factor), minimum: Number(presentation.minimumStock), stock: Number(presentation.currentStock), status: toStatus(presentation.status) })) })
export const mapUnit = (unit: ApiUnit): Unit => ({ id: unit.id, code: unit.code, description: unit.description, status: toStatus(unit.status) })

export async function loadCatalog() { const [products, units] = await Promise.all([api<ApiProduct[]>('/api/products'), api<ApiUnit[]>('/api/products/units')]); return { products: products.map(mapProduct), units: units.map(mapUnit) } }
function productPayload(base: ProductBase, variants: ProductVariant[], units: Unit[]) { return { code: base.code, name: base.name, status: fromStatus(base.status), roles: base.roles.map(role => fromRole[role]), variantType: base.variantType === 'Con variantes' ? 'WITH_VARIANTS' : 'BASIC', immediateConsumption: base.immediateConsumption ?? true, attributes: base.attributes.map((attribute: Attribute) => ({ name: attribute.name, dataType: attribute.type === 'Numérico' ? 'NUMBER' : 'TEXT', suffix: attribute.suffix || null, required: attribute.required, status: fromStatus(attribute.status ?? 'Activo'), useInSubtotal: attribute.useInSubtotal ?? false })), presentations: variants.map(variant => { const unit = units.find(value => value.code.toUpperCase() === variant.unit.toUpperCase()); return { code: variant.code, name: variant.name, unitId: unit?.id, unitCode: unit ? undefined : variant.unit.toUpperCase(), factor: variant.factor, minimumStock: variant.minimum, currentStock: variant.stock, status: fromStatus(variant.status) } }) } }
export async function createCatalogProduct(base: ProductBase, variants: ProductVariant[], units: Unit[]) { const data = await api<ApiProduct>('/api/products', { method: 'POST', body: JSON.stringify(productPayload(base, variants, units)) }); return mapProduct(data) }
export async function updateCatalogProduct(base: ProductBase, variants: ProductVariant[], units: Unit[]) { const data = await api<ApiProduct>(`/api/products/${base.id}`, { method: 'PATCH', body: JSON.stringify(productPayload(base, variants, units)) }); return mapProduct(data) }
export async function deleteCatalogProduct(id: string) { await api<void>(`/api/products/${id}`, { method: 'DELETE' }) }
export async function createCatalogUnit(unit: Omit<Unit, 'id'>) { const data = await api<ApiUnit>('/api/products/units', { method: 'POST', body: JSON.stringify({ code: unit.code, description: unit.description, status: fromStatus(unit.status) }) }); return mapUnit(data) }
export async function updateCatalogUnit(id: string, unit: Omit<Unit, 'id'>) { const data = await api<ApiUnit>(`/api/products/units/${id}`, { method: 'PATCH', body: JSON.stringify({ code: unit.code, description: unit.description, status: fromStatus(unit.status) }) }); return mapUnit(data) }
export async function deleteCatalogUnit(id: string) { await api<void>(`/api/products/units/${id}`, { method: 'DELETE' }) }
