import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Check, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { Button } from '../../../components/ui/button'
import { Dialog } from '../../../components/ui/dialog'
import { ProductionOrderDialog } from '../components/production-order-dialog'
import { completeProductionOrder, createProductionOrder, deleteProductionOrder, listProductionOrders, loadProductionCatalog, type ProductionOrder, type ProductionPayload, type ProductionStatus } from '../services/production-api.service'

type Tab = 'orders' | 'active'
const statusClass: Record<ProductionStatus, string> = { Planificada: 'bg-amber-100 text-amber-700', 'En producción': 'bg-blue-100 text-blue-700', Completada: 'bg-emerald-100 text-emerald-700', Cancelada: 'bg-red-100 text-red-700' }
const Status = ({ status }: { status: ProductionStatus }) => <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold ${statusClass[status]}`}>{status}</span>

export function ProductionPage() {
  const client = useQueryClient(); const [tab, setTab] = useState<Tab>('orders'); const [newOrder, setNewOrder] = useState(false); const [completing, setCompleting] = useState<ProductionOrder | null>(null); const [notice, setNotice] = useState('')
  const ordersQuery = useQuery({ queryKey: ['production'], queryFn: listProductionOrders }); const catalogQuery = useQuery({ queryKey: ['production', 'catalog'], queryFn: loadProductionCatalog })
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 3200) }
  const createMutation = useMutation({ mutationFn: createProductionOrder, onSuccess: order => { client.setQueryData<ProductionOrder[]>(['production'], current => [order, ...(current ?? [])]); void client.invalidateQueries({ queryKey: ['production'] }); setNewOrder(false); notify('Orden creada y tabla sincronizada con la base de datos.') }, onError: error => notify(error instanceof Error ? error.message : 'No se pudo crear la orden.') })
  const completeMutation = useMutation({ mutationFn: ({ id, dispatched, justification }: { id: string; dispatched: boolean; justification?: string }) => completeProductionOrder(id, { outputDispatched: dispatched, outputJustification: justification }), onSuccess: order => { client.setQueryData<ProductionOrder[]>(['production'], current => current?.map(item => item.id === order.id ? order : item) ?? [order]); void client.invalidateQueries({ queryKey: ['production'] }); void client.invalidateQueries({ queryKey: ['production', 'catalog'] }); setCompleting(null); notify('Orden completada: consumo e ingreso de inventario registrados.') }, onError: error => notify(error instanceof Error ? error.message : 'No se pudo completar la orden.') })
  const deleteMutation = useMutation({ mutationFn: deleteProductionOrder, onSuccess: (_, id) => { client.setQueryData<ProductionOrder[]>(['production'], current => current?.filter(item => item.id !== id) ?? []); notify('Orden eliminada.') }, onError: error => notify(error instanceof Error ? error.message : 'Solo se eliminan órdenes planificadas.') })
  const orders = ordersQuery.data ?? []
  return <div className="mx-auto w-full max-w-[1540px]"><nav className="mb-5 flex gap-1 border-b border-border bg-white/70 px-2" aria-label="Secciones de producción"><button onClick={() => setTab('orders')} className={`border-b-2 px-5 py-3 text-[13px] font-medium ${tab === 'orders' ? 'border-brand text-brand' : 'border-transparent text-muted hover:text-ink'}`}>Órdenes de Producción</button><button onClick={() => setTab('active')} className={`border-b-2 px-5 py-3 text-[13px] font-medium ${tab === 'active' ? 'border-brand text-brand' : 'border-transparent text-muted hover:text-ink'}`}>Productos en Producción</button></nav>{tab === 'orders' ? <section className="card"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-sm font-semibold">Órdenes de Producción</h1><p className="mt-1 text-xs text-muted">Planifica y controla la fabricación de productos terminados.</p></div><Button size="sm" onClick={() => setNewOrder(true)} disabled={catalogQuery.isLoading || catalogQuery.isError}><Plus className="h-4 w-4" />Nueva orden</Button></header><OrdersTable orders={orders} loading={ordersQuery.isLoading} failed={ordersQuery.isError} onComplete={setCompleting} onDelete={id => deleteMutation.mutate(id)} /></section> : <ProductionMaterials orders={orders} loading={ordersQuery.isLoading} />}{newOrder && catalogQuery.data && <ProductionOrderDialog catalog={catalogQuery.data} saving={createMutation.isPending} onClose={() => setNewOrder(false)} onSave={async (payload: ProductionPayload) => { await createMutation.mutateAsync(payload).catch(() => undefined) }} />}{completing && <CompleteDialog order={completing} saving={completeMutation.isPending} onClose={() => setCompleting(null)} onComplete={(dispatched, justification) => completeMutation.mutate({ id: completing.id, dispatched, justification })} />}{notice && <div className="fixed bottom-6 right-6 z-[60] max-w-sm rounded-md border border-border border-l-4 border-l-emerald-600 bg-white px-4 py-3 text-sm shadow-panel">{notice}</div>}</div>
}

function OrdersTable({ orders, loading, failed, onComplete, onDelete }: { orders: ProductionOrder[]; loading: boolean; failed: boolean; onComplete: (order: ProductionOrder) => void; onDelete: (id: string) => void }) { return <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[880px] text-left"><thead><tr className="bg-[#f7f9fc] text-[11px] uppercase tracking-[.5px] text-muted">{['N° Orden', 'Producto', 'Presentación', 'Cantidad', 'Fecha de producción', 'Estado', ''].map(value => <th className="border-y border-border px-4 py-3 font-semibold" key={value}>{value}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-10 text-center text-sm text-muted">Cargando órdenes desde la base de datos…</td></tr> : failed ? <tr><td colSpan={7} className="p-10 text-center text-sm text-red-600">No se pudieron cargar las órdenes.</td></tr> : orders.length ? orders.map(order => <tr key={order.id} className="border-b border-border text-[13px]"><td className="px-4 py-3.5 font-mono font-bold text-brand">{order.number}</td><td className="px-4 py-3.5 font-medium">{order.product}</td><td className="px-4 py-3.5 text-slate-600">{order.presentation}</td><td className="px-4 py-3.5 font-mono">{order.quantity} {order.unit}</td><td className="px-4 py-3.5 text-slate-600">{order.date}</td><td className="px-4 py-3.5"><Status status={order.status} />{order.outputDispatched && <span className="ml-2 rounded-full bg-amber-100 px-2 py-1 text-[10px] font-semibold text-amber-700">↗ Salida de inventario</span>}</td><td className="px-4 py-3 text-right">{(order.status === 'En producción' || order.status === 'Planificada') && <Button size="sm" variant="outline" onClick={() => onComplete(order)}><Check className="h-3.5 w-3.5" />Completar</Button>}{(order.status === 'Planificada' || order.status === 'Cancelada') && <button aria-label="Eliminar orden" onClick={() => onDelete(order.id)} className="ml-1 inline-flex h-8 w-8 items-center justify-center rounded border border-red-200 bg-red-50 text-red-600"><Trash2 className="h-3.5 w-3.5" /></button>}</td></tr>) : <tr><td colSpan={7} className="p-10 text-center text-sm text-muted">Aún no hay órdenes de producción registradas.</td></tr>}</tbody></table></div> }

function ProductionMaterials({ orders, loading }: { orders: ProductionOrder[]; loading: boolean }) { const rows = orders.flatMap(order => order.materials.filter(material => material.status === 'Reservado').map(material => ({ order, material }))); return <section className="card"><header><h1 className="text-sm font-semibold">Productos en Producción</h1><p className="mt-1 text-xs text-muted">Insumos reservados por las órdenes activas. Se descuentan al completar la producción.</p></header><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="bg-[#f7f9fc] text-[11px] uppercase tracking-[.5px] text-muted">{['Código', 'Producto', 'Presentación', 'Almacén', 'Cantidad reservada', 'Órdenes activas', 'Estado'].map(value => <th className="border-y border-border px-4 py-3 font-semibold" key={value}>{value}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-10 text-center text-sm text-muted">Cargando reservas…</td></tr> : rows.length ? rows.map(({ order, material }) => <tr key={material.id} className="border-b border-border text-[13px]"><td className="px-4 py-3.5 font-mono text-xs text-muted">{material.code}</td><td className="px-4 py-3.5 font-medium">{material.product}</td><td className="px-4 py-3.5">{material.presentation}</td><td className="px-4 py-3.5">{material.warehouse}</td><td className="px-4 py-3.5 font-mono font-bold text-brand">{material.quantity} {material.unit}</td><td className="px-4 py-3.5"><span className="rounded bg-blue-50 px-2 py-1 font-mono text-xs text-brand">{order.number}</span></td><td className="px-4 py-3.5">{material.immediateConsumption ? <span className="text-xs text-emerald-700">Consumo inmediato</span> : <span className="text-xs text-blue-700">Reservado</span>}</td></tr>) : <tr><td colSpan={7} className="p-10 text-center text-sm text-muted">No hay productos en producción.</td></tr>}</tbody></table></div></section> }

function CompleteDialog({ order, saving, onClose, onComplete }: { order: ProductionOrder; saving: boolean; onClose: () => void; onComplete: (dispatched: boolean, justification?: string) => void }) { const [dispatched, setDispatched] = useState(false); const [justification, setJustification] = useState(''); const valid = !dispatched || justification.trim().length > 0; return <Dialog open title="Completar Orden de Producción" onClose={onClose} footer={<><Button variant="outline" onClick={onClose} disabled={saving}>Cancelar</Button><Button disabled={!valid || saving} onClick={() => onComplete(dispatched, justification.trim() || undefined)}>{saving ? 'Completando…' : 'Confirmar producción'}</Button></>}><div className="space-y-4 text-sm"><div className="rounded-md border border-blue-100 bg-blue-50 p-3"><p className="font-semibold text-ink">{order.product} · {order.quantity} {order.unit}</p><p className="mt-1 text-xs text-muted">Se consumirán los insumos reservados y se registrará el ingreso al almacén {order.warehouse}.</p></div><label className="flex cursor-pointer items-start gap-3 rounded-md border border-border p-3"><input type="checkbox" checked={dispatched} onChange={event => setDispatched(event.target.checked)} className="mt-0.5 h-4 w-4 accent-brand" /><span><span className="block font-medium">Generar salida de inventario</span><span className="mt-0.5 block text-xs text-muted">El producto terminado se registra y luego sale inmediatamente del almacén.</span></span></label>{dispatched && <label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase text-slate-600">Justificación de la salida *</span><textarea value={justification} onChange={event => setJustification(event.target.value)} placeholder="Motivo de la salida de inventario..." className="min-h-24 w-full rounded-md border border-border bg-[#f4f7fb] px-3 py-2.5 text-sm outline-none focus:border-brand focus:bg-white focus:ring-1 focus:ring-brand" /></label>}</div></Dialog> }
