import { useMemo, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { Button } from '../../../components/ui/button'
import { Dialog } from '../../../components/ui/dialog'
import { Input } from '../../../components/ui/input'
import { createCustomsAgent, deleteCustomsAgent, listCustomsAgents, type AgentStatus, type CustomsAgent, updateCustomsAgent } from '../services/customs-agent-api.service'

const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="block"><span className="mb-1.5 block text-[11px] font-semibold uppercase tracking-[.4px] text-slate-600">{label}</span>{children}</label>
const sortAgents = (items: CustomsAgent[]) => [...items].sort((a, b) => a.name.localeCompare(b.name, 'es'))

export function CustomsAgentsPage() {
  const queryClient = useQueryClient()
  const agentsQuery = useQuery({ queryKey: ['customs-agents'], queryFn: listCustomsAgents })
  const agents = agentsQuery.data ?? []
  const [modalItem, setModalItem] = useState<CustomsAgent | null | undefined>(undefined)
  const [search, setSearch] = useState(''); const [notice, setNotice] = useState('')
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2800) }
  const saveMutation = useMutation({ mutationFn: ({ item, editing }: { item: Omit<CustomsAgent, 'id'>; editing?: CustomsAgent }) => editing ? updateCustomsAgent(editing.id, item) : createCustomsAgent(item), onSuccess: (saved) => { queryClient.setQueryData<CustomsAgent[]>(['customs-agents'], current => sortAgents([...(current ?? []).filter(item => item.id !== saved.id), saved])); void queryClient.invalidateQueries({ queryKey: ['customs-agents'] }); setSearch(''); setModalItem(undefined); notify('Agente guardado y sincronizado con la base de datos') }, onError: error => notify(error instanceof Error ? error.message : 'No se pudo guardar el agente') })
  const removeMutation = useMutation({ mutationFn: deleteCustomsAgent, onSuccess: (_, id) => { queryClient.setQueryData<CustomsAgent[]>(['customs-agents'], current => current?.filter(item => item.id !== id) ?? []); void queryClient.invalidateQueries({ queryKey: ['customs-agents'] }); notify('Agente eliminado de la base de datos') }, onError: error => notify(error instanceof Error ? error.message : 'No se pudo eliminar el agente') })
  const filtered = useMemo(() => agents.filter(agent => `${agent.name} ${agent.ruc} ${agent.contact} ${agent.email}`.toLowerCase().includes(search.toLowerCase())), [agents, search])
  return <div className="mx-auto max-w-none"><section className="rounded-[10px] border border-border bg-white p-6 shadow-card"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-sm font-semibold">Agentes de Aduana</h1><p className="mt-1 text-xs text-muted">Agentes y contactos disponibles para operaciones de importación.</p></div><Button size="sm" onClick={() => setModalItem(null)}><Plus className="h-4 w-4" />Nuevo Agente</Button></header><div className="relative mt-5 max-w-sm"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted" /><Input className="h-9 pl-9" placeholder="Buscar agente o RUC…" value={search} onChange={event => setSearch(event.target.value)} /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[930px] text-left"><thead><tr className="bg-[#f7f9fc] text-[11px] uppercase tracking-[.5px] text-muted">{['Nombre / Razón Social', 'RUC', 'Contacto', 'Teléfono / Email', 'Estado', ''].map(value => <th className="border-y border-border px-4 py-3" key={value}>{value}</th>)}</tr></thead><tbody>{agentsQuery.isLoading ? <tr><td colSpan={6} className="p-10 text-center text-sm text-muted">Cargando agentes desde la base de datos…</td></tr> : agentsQuery.isError ? <tr><td colSpan={6} className="p-10 text-center text-sm text-red-600">No se pudieron cargar los agentes.</td></tr> : filtered.length ? filtered.map(agent => <tr className="border-b border-border text-[13px] text-slate-700" key={agent.id}><td className="px-4 py-3.5 font-medium">{agent.name}</td><td className="px-4 py-3.5 font-mono text-xs">{agent.ruc || '—'}</td><td className="px-4 py-3.5">{agent.contact || '—'}</td><td className="px-4 py-3.5"><span>{agent.phone || '—'}</span>{agent.email && <small className="mt-0.5 block text-xs text-muted">{agent.email}</small>}</td><td className="px-4 py-3.5"><StatusBadge status={agent.status} /></td><td className="px-4 py-3.5 text-right"><IconButton label="Editar agente" onClick={() => setModalItem(agent)}><Pencil className="h-3.5 w-3.5" /></IconButton><IconButton label="Eliminar agente" danger onClick={() => removeMutation.mutate(agent.id)}><Trash2 className="h-3.5 w-3.5" /></IconButton></td></tr>) : <tr><td colSpan={6} className="p-10 text-center text-sm text-muted">No se encontraron agentes de aduana.</td></tr>}</tbody></table></div></section>{modalItem !== undefined && <AgentDialog item={modalItem ?? undefined} onClose={() => setModalItem(undefined)} onSave={async item => { await saveMutation.mutateAsync({ item, editing: modalItem ?? undefined }).catch(() => undefined) }} />}{notice && <Toast>{notice}</Toast>}</div>
}

function AgentDialog({ item, onClose, onSave }: { item?: CustomsAgent; onClose: () => void; onSave: (agent: Omit<CustomsAgent, 'id'>) => Promise<void> }) {
  const [name, setName] = useState(item?.name ?? ''); const [ruc, setRuc] = useState(item?.ruc ?? ''); const [contact, setContact] = useState(item?.contact ?? ''); const [phone, setPhone] = useState(item?.phone ?? ''); const [email, setEmail] = useState(item?.email ?? ''); const [status, setStatus] = useState<AgentStatus>(item?.status ?? 'Activo'); const [saving, setSaving] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; setSaving(true); try { await onSave({ name: name.trim(), ruc: ruc.trim(), contact: contact.trim(), phone: phone.trim(), email: email.trim(), status }) } finally { setSaving(false) } }
  return <Dialog open title={item ? 'Editar Agente de Aduana' : 'Nuevo Agente de Aduana'} onClose={onClose} footer={<><Button variant="outline" onClick={onClose} disabled={saving}>Cancelar</Button><Button form="agent-form" type="submit" disabled={saving}>{saving ? 'Guardando…' : 'Guardar'}</Button></>}><form id="agent-form" className="grid gap-4 md:grid-cols-2" onSubmit={submit}><div className="md:col-span-2"><Field label="Nombre / Razón Social *"><Input required value={name} onChange={event => setName(event.target.value)} placeholder="ej. Aduanas Callao S.A.C." /></Field></div><Field label="RUC"><Input value={ruc} onChange={event => setRuc(event.target.value)} /></Field><Field label="Persona de contacto"><Input value={contact} onChange={event => setContact(event.target.value)} /></Field><Field label="Teléfono"><Input value={phone} onChange={event => setPhone(event.target.value)} /></Field><Field label="Correo"><Input type="email" value={email} onChange={event => setEmail(event.target.value)} /></Field><Field label="Estado"><select className="h-10 w-full rounded-md border border-border bg-[#f4f7fb] px-3 text-sm" value={status} onChange={event => setStatus(event.target.value as AgentStatus)}><option>Activo</option><option>Inactivo</option></select></Field></form></Dialog>
}
function StatusBadge({ status }: { status: AgentStatus }) { return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${status === 'Activo' ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'}`}>{status}</span> }
function IconButton({ children, label, danger, onClick }: { children: React.ReactNode; label: string; danger?: boolean; onClick: () => void }) { return <button title={label} aria-label={label} onClick={onClick} className={`ml-1 inline-flex h-9 w-10 items-center justify-center rounded-md border ${danger ? 'border-red-300 bg-red-50 text-red-500' : 'border-border bg-white text-slate-700'}`}>{children}</button> }
function Toast({ children }: { children: React.ReactNode }) { return <div className="fixed bottom-6 right-6 z-[60] rounded-md border border-border border-l-4 border-l-emerald-600 bg-white px-4 py-3 text-sm shadow-panel">{children}</div> }
