import { accessToken, api, apiBaseUrl, ApiError } from '../../../lib/api-client'

export type PurchaseLine = { id: string; productId: string; presentationId: string; warehouseId: string; product: string; presentation: string; warehouse: string; unit: string; quantity: number; price: number }
export type Purchase = { id: string; number: string; supplier: string; date: string; receiptDate: string; invoice: string; currency: 'PEN' | 'USD'; total: number; status: 'Borrador' | 'Aprobada' | 'Recibida' | 'Anulada'; lines: PurchaseLine[]; attachments: string[] }
export type PurchaseCatalog = { suppliers: { id: string; name: string; taxId: string | null }[]; products: { id: string; name: string; presentations: { id: string; name: string; unit: { code: string } }[] }[]; warehouses: { id: string; name: string }[] }
export type UploadedPurchaseDocument = { fileName: string; mimeType: string; size: number; storageKey: string }

type ApiPurchase = { id: string; number: string; supplierInvoiceNumber: string; purchaseDate: string; receiptDate: string; currency: 'PEN' | 'USD'; total: string | number; status: 'DRAFT' | 'APPROVED' | 'RECEIVED' | 'CANCELLED'; supplier: { name: string }; documents: { fileName: string }[]; items: { id: string; productId: string; presentationId: string; warehouseId: string; quantity: string | number; unitPrice: string | number; product: { name: string }; presentation: { name: string; unit: { code: string } }; warehouse: { name: string } }[] }
const status: Record<ApiPurchase['status'], Purchase['status']> = { DRAFT: 'Borrador', APPROVED: 'Aprobada', RECEIVED: 'Recibida', CANCELLED: 'Anulada' }
const mapPurchase = (purchase: ApiPurchase): Purchase => ({ id: purchase.id, number: purchase.number, supplier: purchase.supplier.name, date: purchase.purchaseDate.slice(0, 10), receiptDate: purchase.receiptDate.slice(0, 10), invoice: purchase.supplierInvoiceNumber, currency: purchase.currency, total: Number(purchase.total), status: status[purchase.status], attachments: purchase.documents.map(document => document.fileName), lines: purchase.items.map(line => ({ id: line.id, productId: line.productId, presentationId: line.presentationId, warehouseId: line.warehouseId, product: line.product.name, presentation: line.presentation.name, warehouse: line.warehouse.name, unit: line.presentation.unit.code, quantity: Number(line.quantity), price: Number(line.unitPrice) })) })
export async function listPurchases() { return (await api<ApiPurchase[]>('/api/purchases')).map(mapPurchase) }
export async function loadPurchaseCatalog() { return api<PurchaseCatalog>('/api/purchases/catalog') }
export async function createPurchase(payload: { supplierId: string; supplierInvoiceNumber: string; purchaseDate: string; receiptDate: string; currency: 'PEN' | 'USD'; items: { productId: string; presentationId: string; warehouseId: string; quantity: number; unitPrice: number }[]; documents: UploadedPurchaseDocument[] }) { return mapPurchase(await api<ApiPurchase>('/api/purchases', { method: 'POST', body: JSON.stringify(payload) })) }
export async function uploadPurchaseDocument(file: File) { const response = await fetch(`${apiBaseUrl}/api/purchases/documents`, { method: 'POST', headers: { 'Content-Type': 'application/pdf', 'X-File-Name': encodeURIComponent(file.name), ...(accessToken() && { Authorization: `Bearer ${accessToken()}` }) }, body: file }); const body = await response.json().catch(() => null); if (!response.ok) throw new ApiError(body?.error?.message ?? 'No se pudo subir el PDF.', response.status); return body.data as UploadedPurchaseDocument }
export async function removePurchaseDocument(storageKey: string) { await api<void>('/api/purchases/documents', { method: 'DELETE', body: JSON.stringify({ storageKey }) }) }
export async function deletePurchase(id: string) { await api<void>(`/api/purchases/${id}`, { method: 'DELETE' }) }
