import { Prisma, PurchaseStatus, ProductStatus, SupplierType } from '@prisma/client'
import { prisma } from '../../../infrastructure/database/prisma.client.js'
import { AppError } from '../../../shared/errors/app-error.js'
import { purchaseRepository } from '../repositories/purchase.repository.js'
import type { PurchaseInput, UpdatePurchaseInput } from '../schemas/purchase.schema.js'
const decimal = (value: number) => new Prisma.Decimal(value)
const nextNumber = () => `OC-${Date.now().toString().slice(-6)}`
const totalOf = (items: { quantity: number; unitPrice: number }[]) => items.reduce((sum, line) => sum.plus(decimal(line.quantity).mul(decimal(line.unitPrice))), new Prisma.Decimal(0))
const transaction = <T>(callback: (db: Prisma.TransactionClient) => Promise<T>) => prisma.$transaction(callback, { maxWait: 10_000, timeout: 30_000 })

async function validateReferences(companyId: string, input: Pick<PurchaseInput, 'supplierId' | 'items'>) {
  const supplier = await prisma.supplier.findFirst({ where: { id: input.supplierId, companyId, type: SupplierType.NATIONAL, status: ProductStatus.ACTIVE } })
  if (!supplier) throw new AppError('SUPPLIER_NOT_AVAILABLE', 'Selecciona un proveedor nacional activo.', 422)
  const presentationIds = [...new Set(input.items.map(value => value.presentationId))]; const warehouseIds = [...new Set(input.items.map(value => value.warehouseId))]
  const [presentations, warehouses] = await Promise.all([prisma.productPresentation.findMany({ where: { id: { in: presentationIds }, status: ProductStatus.ACTIVE } }), prisma.warehouse.findMany({ where: { id: { in: warehouseIds }, companyId, status: ProductStatus.ACTIVE } })])
  if (presentations.length !== presentationIds.length || warehouses.length !== warehouseIds.length) throw new AppError('PURCHASE_REFERENCE_INVALID', 'Producto, presentación o almacén no disponible.', 422)
  for (const line of input.items) { const presentation = presentations.find(value => value.id === line.presentationId); if (!presentation || presentation.productId !== line.productId) throw new AppError('PURCHASE_PRODUCT_MISMATCH', 'La presentación no corresponde al producto seleccionado.', 422) }
}
async function applyReceipt(db: Prisma.TransactionClient, purchase: { number: string; items: { productId: string; presentationId: string; warehouseId: string; quantity: Prisma.Decimal; presentation: { factor: Prisma.Decimal } }[] }) { for (const line of purchase.items) { const quantity = line.quantity.mul(line.presentation.factor); await db.stock.upsert({ where: { productId_warehouseId: { productId: line.productId, warehouseId: line.warehouseId } }, create: { productId: line.productId, warehouseId: line.warehouseId, quantity }, update: { quantity: { increment: quantity } } }); await db.productPresentation.update({ where: { id: line.presentationId }, data: { currentStock: { increment: line.quantity } } }); await db.inventoryMovement.create({ data: { productId: line.productId, warehouseId: line.warehouseId, type: 'PURCHASE_RECEIPT', quantity, reference: purchase.number, note: `Recepción de compra ${purchase.number}` } }) } }
const receiptInclude = { items: { include: { presentation: true } } } satisfies Prisma.PurchaseInclude
export const purchaseService = {
  list(companyId: string, filters: { status?: PurchaseStatus; supplierId?: string; search?: string }) { const where: Prisma.PurchaseWhereInput = { companyId, ...(filters.status && { status: filters.status }), ...(filters.supplierId && { supplierId: filters.supplierId }), ...(filters.search && { OR: [{ number: { contains: filters.search, mode: 'insensitive' } }, { supplierInvoiceNumber: { contains: filters.search, mode: 'insensitive' } }, { supplier: { name: { contains: filters.search, mode: 'insensitive' } } }] }) }; return purchaseRepository.findMany(where) },
  async getById(companyId: string, id: string) { const purchase = await purchaseRepository.findById(id, companyId); if (!purchase) throw new AppError('PURCHASE_NOT_FOUND', 'Compra no encontrada.', 404); return purchase },
  catalog: (companyId: string) => purchaseRepository.catalog(companyId),
  async create(companyId: string, input: PurchaseInput) { await validateReferences(companyId, input); if (await purchaseRepository.findDuplicateInvoice(companyId, input.supplierId, input.supplierInvoiceNumber)) throw new AppError('SUPPLIER_INVOICE_EXISTS', 'Ese comprobante ya fue registrado para el proveedor.', 409); return transaction(async db => { const created = await purchaseRepository.create(db, { company: { connect: { id: companyId } }, supplier: { connect: { id: input.supplierId } }, number: nextNumber(), supplierInvoiceNumber: input.supplierInvoiceNumber, purchaseDate: input.purchaseDate, receiptDate: input.receiptDate, currency: input.currency, status: input.status, total: totalOf(input.items), items: { create: input.items.map(line => ({ product: { connect: { id: line.productId } }, presentation: { connect: { id: line.presentationId } }, warehouse: { connect: { id: line.warehouseId } }, quantity: decimal(line.quantity), unitPrice: decimal(line.unitPrice) })) }, documents: { create: input.documents } }); if (created.status === PurchaseStatus.RECEIVED) { const receipt = await db.purchase.findUniqueOrThrow({ where: { id: created.id }, include: receiptInclude }); await applyReceipt(db, receipt) }; return created }) },
  async update(companyId: string, id: string, input: UpdatePurchaseInput) { const current = await this.getById(companyId, id); if (current.status !== PurchaseStatus.DRAFT) throw new AppError('PURCHASE_LOCKED', 'Solo se pueden editar compras en borrador.', 409); const items = input.items ?? current.items.map(line => ({ productId: line.productId, presentationId: line.presentationId, warehouseId: line.warehouseId, quantity: Number(line.quantity), unitPrice: Number(line.unitPrice) })); await validateReferences(companyId, { supplierId: input.supplierId ?? current.supplierId, items }); return transaction(db => purchaseRepository.update(db, id, { ...(input.supplierId && { supplier: { connect: { id: input.supplierId } } }), ...(input.supplierInvoiceNumber && { supplierInvoiceNumber: input.supplierInvoiceNumber }), ...(input.purchaseDate && { purchaseDate: input.purchaseDate }), ...(input.receiptDate && { receiptDate: input.receiptDate }), ...(input.currency && { currency: input.currency }), ...(input.status && { status: input.status }), ...(input.items && { total: totalOf(input.items), items: { deleteMany: {}, create: input.items.map(line => ({ product: { connect: { id: line.productId } }, presentation: { connect: { id: line.presentationId } }, warehouse: { connect: { id: line.warehouseId } }, quantity: decimal(line.quantity), unitPrice: decimal(line.unitPrice) })) } }), ...(input.documents && { documents: { deleteMany: {}, create: input.documents } }) })) },
  async receive(companyId: string, id: string) { const current = await this.getById(companyId, id); if (current.status !== PurchaseStatus.DRAFT && current.status !== PurchaseStatus.APPROVED) throw new AppError('PURCHASE_NOT_RECEIVABLE', 'La compra no está disponible para recepción.', 409); return transaction(async db => { const receipt = await db.purchase.findUniqueOrThrow({ where: { id }, include: receiptInclude }); await applyReceipt(db, receipt); return purchaseRepository.update(db, id, { status: PurchaseStatus.RECEIVED }) }) },
  async remove(companyId: string, id: string) { const current = await this.getById(companyId, id); if (current.status !== PurchaseStatus.DRAFT) throw new AppError('PURCHASE_LOCKED', 'Solo se pueden eliminar compras en borrador.', 409); await purchaseRepository.remove(prisma, id) },
}
