import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Eye, Pencil, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { Button } from '../../../components/ui/button'
import { Dialog } from '../../../components/ui/dialog'
import { ImportDialog } from '../components/import-dialog'
import { createImport, deleteImport, listImports, loadImportCatalog, type ImportPayload, type ImportRecord, updateImport } from '../services/import-api.service'

export function ImportsPage() {
  const queryClient = useQueryClient()
  const importsQuery = useQuery({ queryKey: ['imports'], queryFn: listImports })
  const catalogQuery = useQuery({ queryKey: ['imports', 'catalog'], queryFn: loadImportCatalog })
  const [modal, setModal] = useState<'form' | 'detail' | null>(null)
  const [editing, setEditing] = useState<ImportRecord>()
  const [notice, setNotice] = useState('')
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 3200) }
  const saveMutation = useMutation({ mutationFn: ({ id, payload }: { id?: string; payload: ImportPayload }) => id ? updateImport(id, payload) : createImport(payload), onSuccess: saved => { queryClient.setQueryData<ImportRecord[]>(['imports'], current => { const records = current ?? []; return editing ? records.map(record => record.id === saved.id ? saved : record) : [saved, ...records] }); void queryClient.invalidateQueries({ queryKey: ['imports'] }); setModal(null); notify(editing ? 'Importación actualizada y tabla sincronizada' : 'Importación registrada y tabla sincronizada') }, onError: error => notify(error instanceof Error ? error.message : 'No se pudo registrar la importación') })
  const deleteMutation = useMutation({ mutationFn: deleteImport, onSuccess: (_, id) => { queryClient.setQueryData<ImportRecord[]>(['imports'], current => current?.filter(record => record.id !== id) ?? []); notify('Importación eliminada') }, onError: error => notify(error instanceof Error ? error.message : 'No se puede eliminar esta importación') })
  const records = importsQuery.data ?? []
  return <div className="mx-auto max-w-7xl"><section className="card"><header className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-sm font-semibold">Importaciones</h1><Button size="sm" disabled={catalogQuery.isLoading || catalogQuery.isError} onClick={() => { setEditing(undefined); setModal('form') }}><Plus className="h-4 w-4" />Nueva Importación</Button></header><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1000px] text-left"><thead><tr className="bg-[#f7f9fc] text-[11px] uppercase tracking-[.5px] text-muted">{['N° Orden', 'Proveedor', 'País', 'Contenedor', 'Estado', 'F. Pedido', 'Total USD', ''].map(value => <th className="border-y border-border px-4 py-3" key={value}>{value}</th>)}</tr></thead><tbody>{importsQuery.isLoading ? <tr><td colSpan={8} className="p-10 text-center text-sm text-muted">Cargando importaciones desde la base de datos…</td></tr> : importsQuery.isError ? <tr><td colSpan={8} className="p-10 text-center text-sm text-red-600">No se pudieron cargar las importaciones.</td></tr> : records.length ? records.map(record => <tr className="border-b border-border text-[13px] text-slate-700" key={record.id}><td className="px-4 py-3.5 font-mono">{record.number}</td><td className="px-4 py-3.5">{record.supplier}</td><td className="px-4 py-3.5">{record.country}</td><td className="px-4 py-3.5 font-mono">{record.container}</td><td className="px-4 py-3.5"><StatusBadge status={record.status} /></td><td className="px-4 py-3.5">{record.date || '—'}</td><td className="px-4 py-3.5 font-mono">USD {record.total.toFixed(2)}</td><td className="whitespace-nowrap px-4 py-3.5 text-right"><Button size="sm" variant="outline" onClick={() => { setEditing(record); setModal('detail') }}><Eye className="h-3.5 w-3.5" />Ver</Button>{record.status !== 'Recibido' && <><IconButton onClick={() => { setEditing(record); setModal('form') }}><Pencil className="h-3.5 w-3.5" /></IconButton><IconButton danger onClick={() => deleteMutation.mutate(record.id)}><Trash2 className="h-3.5 w-3.5" /></IconButton></>}</td></tr>) : <tr><td colSpan={8} className="p-10 text-center text-sm text-muted">Aún no hay importaciones registradas.</td></tr>}</tbody></table></div></section>{modal === 'form' && catalogQuery.data && <ImportDialog catalog={catalogQuery.data} item={editing} saving={saveMutation.isPending} onClose={() => setModal(null)} onSave={async payload => { await saveMutation.mutateAsync({ id: editing?.id, payload }).catch(() => undefined) }} />}{modal === 'detail' && editing && <ImportDetail record={editing} onClose={() => setModal(null)} />}{notice && <div className="fixed bottom-6 right-6 z-[60] rounded-md border border-border border-l-4 border-l-emerald-600 bg-white px-4 py-3 text-sm shadow-panel">{notice}</div>}</div>
}
function StatusBadge({ status }: { status: ImportRecord['status'] }) { return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${status === 'Recibido' ? 'bg-emerald-100 text-emerald-700' : status === 'En tránsito' ? 'bg-blue-100 text-blue-700' : 'bg-red-100 text-red-700'}`}>{status}</span> }
function IconButton({ children, danger, onClick }: { children: React.ReactNode; danger?: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={`ml-1 inline-flex h-9 w-10 items-center justify-center rounded-md border ${danger ? 'border-red-300 bg-red-50 text-red-500' : 'border-border bg-white text-slate-700'}`}>{children}</button> }
function ImportDetail({ record, onClose }: { record: ImportRecord; onClose: () => void }) { return <Dialog open title={`Importación ${record.number}`} onClose={onClose} footer={<Button onClick={onClose}>Cerrar</Button>}><div className="grid gap-3 text-sm sm:grid-cols-2"><p><b>Proveedor:</b> {record.supplier}</p><p><b>País:</b> {record.country}</p><p><b>Contenedor:</b> {record.container}</p><p><b>DUA:</b> {record.dua}</p><p><b>Estado:</b> <StatusBadge status={record.status} /></p><p><b>Total:</b> USD {record.total.toFixed(2)}</p></div><div className="mt-5 overflow-x-auto rounded-md border border-border"><table className="w-full min-w-[600px] text-sm"><thead className="bg-[#f7f9fc] text-left text-[11px] uppercase text-muted"><tr><th className="p-3">Producto</th><th>Presentación</th><th>Almacén</th><th>Cant.</th><th>Costo USD</th></tr></thead><tbody>{record.lines.map(line => <tr className="border-t border-border" key={line.id}><td className="p-3">{line.product}</td><td>{line.presentation}</td><td>{line.warehouse}</td><td>{line.quantity}</td><td className="font-mono">{line.unitCostUsd.toFixed(2)}</td></tr>)}</tbody></table></div></Dialog> }
