import { api } from '../../../lib/api-client'

export type ImportStatus = 'En tránsito' | 'Recibido' | 'Cancelado'
export type ImportLine = { id: string; productId: string; presentationId: string; warehouseId: string; product: string; presentation: string; warehouse: string; unit: string; quantity: number; unitCostUsd: number }
export type ImportRecord = { id: string; number: string; supplier: string; country: string; container: string; dua: string; purchaseOrder: string; status: ImportStatus; date: string; total: number; currency: 'USD' | 'PEN'; customsAgent: string | null; customsCostUsd: number; customsCostPen: number; lines: ImportLine[]; attachments: { name: string; link: string | null }[] }
export type ImportCatalog = { suppliers: { id: string; name: string }[]; customsAgents: { id: string; name: string }[]; products: { id: string; name: string; presentations: { id: string; name: string; unit: { code: string } }[] }[]; warehouses: { id: string; name: string }[] }
export type ImportPayload = { supplierId: string; customsAgentId?: string | null; containerNumber: string; duaNumber: string; purchaseOrderNumber: string; countryOfOrigin: string; status: 'IN_TRANSIT' | 'RECEIVED' | 'CANCELLED'; currency: 'USD' | 'PEN'; arrivalDate?: string | null; customsCostUsd: number; customsCostPen: number; items: { productId: string; presentationId: string; warehouseId: string; quantity: number; unitCostUsd: number }[]; documents: { fileName: string; mimeType?: string; size?: number; linkUrl?: string }[] }

type ApiImport = { id: string; number: string; containerNumber: string; duaNumber: string; purchaseOrderNumber: string; countryOfOrigin: string; status: 'IN_TRANSIT' | 'RECEIVED' | 'CANCELLED'; currency: 'USD' | 'PEN'; arrivalDate: string | null; customsCostUsd: string | number; customsCostPen: string | number; totalUsd: string | number; supplier: { name: string }; customsAgent: { name: string } | null; documents: { fileName: string; linkUrl: string | null }[]; items: { id: string; productId: string; presentationId: string; warehouseId: string; quantity: string | number; unitCostUsd: string | number; product: { name: string }; presentation: { name: string; unit: { code: string } }; warehouse: { name: string } }[] }
const statuses: Record<ApiImport['status'], ImportStatus> = { IN_TRANSIT: 'En tránsito', RECEIVED: 'Recibido', CANCELLED: 'Cancelado' }
const mapImport = (record: ApiImport): ImportRecord => ({ id: record.id, number: record.number, supplier: record.supplier.name, country: record.countryOfOrigin, container: record.containerNumber, dua: record.duaNumber, purchaseOrder: record.purchaseOrderNumber, status: statuses[record.status], date: record.arrivalDate?.slice(0, 10) ?? '', total: Number(record.totalUsd), currency: record.currency, customsAgent: record.customsAgent?.name ?? null, customsCostUsd: Number(record.customsCostUsd), customsCostPen: Number(record.customsCostPen), attachments: record.documents.map(document => ({ name: document.fileName, link: document.linkUrl })), lines: record.items.map(line => ({ id: line.id, productId: line.productId, presentationId: line.presentationId, warehouseId: line.warehouseId, product: line.product.name, presentation: line.presentation.name, warehouse: line.warehouse.name, unit: line.presentation.unit.code, quantity: Number(line.quantity), unitCostUsd: Number(line.unitCostUsd) })) })

export async function listImports() { return (await api<ApiImport[]>('/api/imports')).map(mapImport) }
export async function loadImportCatalog() { return api<ImportCatalog>('/api/imports/catalog') }
export async function createImport(payload: ImportPayload) { return mapImport(await api<ApiImport>('/api/imports', { method: 'POST', body: JSON.stringify(payload) })) }
export async function updateImport(id: string, payload: Partial<ImportPayload>) { return mapImport(await api<ApiImport>(`/api/imports/${id}`, { method: 'PATCH', body: JSON.stringify(payload) })) }
export async function receiveImport(id: string) { return mapImport(await api<ApiImport>(`/api/imports/${id}/receive`, { method: 'POST' })) }
export async function deleteImport(id: string) { await api<void>(`/api/imports/${id}`, { method: 'DELETE' }) }
